### ISSUE TITLE
Create initial user management administration page

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#10]
As a PM administrator, I want the ability to manage my users in my system. This system should allow the creation, view, update and delete of users in the system.

**Functionality:**
... dropdown on the furthest right column 
- View
- Edit
- Disable
- Delete

**3 Options to Edit User Profiles**

Option 1
- User can scroll over a row 
- Row with user info will change to darker color background to highlight so that you can select it
- Click on it row once to open profile page

Option 2 
- User can click on 3 dots (…) on each row on the right side of page (after all columns)
- Dropdown will appear with choices
1 - View User
User can view the user's profile summary (with 7 default fields - username, full name, status, role, last login, # cases, due date) without ability to edit
If user wants to edit, they can select Edit button from here
Edit button will take them to regular Edit User page
2 - Edit User
3 - Activate/ Deactivate User 
- Scroll down and click activate or deactivate to change user
- After activating deactivating user, 'You successfully (de)activated username x' message will display 
- If user is inactive — dropdown says Activate
- If user is currently active — dropdown says Deactivate
4 - Delete User
- Choose this option and 'Do you really want to delete username x?' message will display 
- Window will have 2 buttons - CANCEL button on left side, DELETE button on right side
- If user selects CANCEL button, Delete User window message will close
- If user selects DELETE button, 'You successfully deleted username x' message will display 

Option 3 - User can select one checkbox on row to the left of the columns - to select one user
- New menu w/ icons appears on top of the table to the left of the button 
- Icons show the same 4 choices as drop-down menu - View, Edit, Activate/ Inactivate, Delete

User can select multiple rows by checking multiple boxes
- View and Edit icons will disappear 
- There will be 3 icons -  Activate, Deactivate and Delete

<img width="1061" alt="screen shot 2018-06-01 at 1 24 09 pm" src="https://user-images.githubusercontent.com/39599643/40862270-d908b384-65a0-11e8-97d4-d6d410c1d6ae.png">

**Comment by velkymx** [comment]
Create new role modal:

![screenshot 2018-06-05 13 13 05](https://user-images.githubusercontent.com/535300/41000242-39d40320-68c2-11e8-8ee4-fdc64298c23a.png)

**Comment by velkymx** [comment]
For the checkboxes. Once you check a box, then activate, deactivate, remove multiple roles button appear and will modify the selected records.

**Comment by tdondich** [comment]
@meadrat The "DUE" column in users actually represents the user's expiration date (for temp users).  So, for column header, going to use "Expires"
