### ISSUE TITLE
Vuetable Columns

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1011]
Below are the columns and order for each section.

- [x] Request. Name, Status, Participants, Started, Completed
- [x] Tasks. Name, Request, Assignee, Due
- [x] Processes. Name, Category, Status, Owner (bubble only), Modified, Created
- [x] Process Categories: Name, Status, # Processes, Modified, Created
- [x] Scripts. Name, Description, Language, Modified, Created
- [x] Screens. Name, Description, Type, Modified, Created
- [x] Environment Variables. Name, Description, Modified, Created
- [x] Users. Username, Full Name, Status, Modified, Created, Last Log In
- [x] Groups. Name, Description, Status, # Users, Modified, Created

**Comment by milaendo** [comment]
to do: 
-[ ] processes owner bubbles
