### ISSUE TITLE
Cant edit script Config info

### ISSUE THREAD

**Issue by milaendo** [ProcessMaker/bpm#1030]
There is currently noway to change the name, language, or anything like that.

**Comment by caleeli** [comment]
@milaendo could you provide more detail, I've just tested it with the last develop code, and it was able to config the script in the Modeler and in the Admin tab.

**Comment by milaendo** [comment]
@caleeli in all of the other tables there is an edit page to change the title, last I checked there was not one in the script table. I could be incorrect though!

**Comment by caleeli** [comment]
Related to #1049
