### ISSUE TITLE
New Process throws Error

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1032]
In the modeler, when you save it throw the error:
``requests.cancel permission does not exist``
when you click save
<img width="763" alt="screenshot 2018-12-17 06 29 17" src="https://user-images.githubusercontent.com/535300/50093324-2efc9100-01c5-11e9-8c36-0eae516a3adb.png">

**Comment by milaendo** [comment]
@ryancooley and I tried to replicate and cannot. We believe it was resolved.
