### ISSUE TITLE
Edit Process Broken

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1044]
/processes/1/edit

Oops!
The page you are looking for could not be found

**Comment by caleeli** [comment]
Could not be replicated in the last develop branch:

![image](https://user-images.githubusercontent.com/8028650/50157681-76a81900-02a8-11e9-88c3-a4f5607c8655.png)

**Comment by milaendo** [comment]
confirmed, this is working in the current develop.
