### ISSUE TITLE
New User Permissions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1056]
When you create a new user and select all permissions NOT an admin flag user, then log in as that user. Should I be able to see the admin section? and should I be able to see this count in the request page?

**Comment by nolanpro** [comment]
@velkymx Its possible the user could be not admin but still have the permissions to edit users and groups, but not sure if thats the desired behavior. We could check if they a have at least one of the permissions for a menu and if they don't, we hide it.
