### ISSUE TITLE
Pagination Formatting

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1061]
Add padding to the left and right of the pagination so the next isn't right up against the border. 

![screenshot 2018-12-18 09 05 46](https://user-images.githubusercontent.com/535300/50170181-28911680-02a4-11e9-9710-16c4ab844e81.png)

**Comment by nolanpro** [comment]
Can't reproduce. Are you seeing this on a specific page? I tried a few different ones.
![image](https://user-images.githubusercontent.com/2546850/50188054-1a0f2300-02d5-11e9-923f-f77bde3f6d5f.png)
