### ISSUE TITLE
Tooltips on Action Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1084]
Check alignment of tool tips. Make sure the alignment is centered on the icon on each grid.

**Comment by milaendo** [comment]
![screen shot 2018-12-21 at 11 03 27 am](https://user-images.githubusercontent.com/29641725/50359042-259a5e00-0510-11e9-9eee-5417d2e003f8.png)
![screen shot 2018-12-21 at 11 03 18 am](https://user-images.githubusercontent.com/29641725/50359043-259a5e00-0510-11e9-83a8-2ffc49c7581b.png)
![screen shot 2018-12-21 at 11 03 44 am](https://user-images.githubusercontent.com/29641725/50359044-259a5e00-0510-11e9-8e1c-606bfe6dec8f.png)
![screen shot 2018-12-21 at 11 03 36 am](https://user-images.githubusercontent.com/29641725/50359045-259a5e00-0510-11e9-9fa9-98523628925d.png)
I was not able to reproduce this bug
