### ISSUE TITLE
Avatar enhancements

### ISSUE THREAD

**Issue by milaendo** [ProcessMaker/bpm#1141]
Be sure all avatars in the tables do not display the users name
try out the avatar package from vue

**Comment by velkymx** [comment]
Check out https://eliep.github.io/vue-avatar/

**Comment by velkymx** [comment]
and https://github.com/lossendae/vue-avatar

**Comment by milaendo** [comment]
to update: @ryancooley and I were able to find a fix for the nav bar breaking when a user does not have a first or last name. Now we just need to decide if we want to take on the project of replacing the avatar component.
