### ISSUE TITLE
Permission Gates

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1147]
In keeping with the Laravel Way we need to move to use the Laravel Gates. This will allow a more central and explicit way to manage application access.

https://laravel-news.com/authorization-gates

https://laravel.com/docs/5.7/authorization#gates

https://code.tutsplus.com/tutorials/gates-and-policies-in-laravel--cms-29780

https://laracasts.com/series/laravel-from-scratch-2018/episodes/27

**Details**

- By default, the action of the UI is to deny access.
- Routes that are not protected (other than having an active user): home, requests, tasks, profile, profile edit, notifications
- Does not apply to the Auth routes
- Access is cumulative - if an user is assigned to a group that user gains access from the group
- Groups need to have the same permissions tab as the users

**Global Permissions** - Global permissions are permissions assigned to the user via the group or the user permissions.

**Requests area** - by default I can see only requests I have access to via my participation. The only route that is different is the All Requests area (/requests/all) where all requests are available. 

**Gates**

- [x] /requests/all - is restricted to only people with access

- [x] /processes - is restricted to only people with access
- [x] create process - is restricted to only people with access
- [x] edit process (including modeling) - is restricted to only people with access
- [x] archive process - is restricted to only people with access

- [x] /processes/categories - is restricted to only people with access
- [x] category add - is restricted to only people with access
- [x] category edit - is restricted to only people with access
- [x] category delete - is restricted to only people with access

- [x] /processes/scripts/ - is restricted to only people with access
- [x] create scripts - is restricted to only people with access
- [x] edit / config scripts (including the editor) - is restricted to only people with access
- [x] delete scripts - is restricted to only people with access

- [x] /processes/screens/ - is restricted to only people with access
- [x] create screens - is restricted to only people with access
- [x] edit / config screens (including the editor) - is restricted to only people with access
- [x] delete screens - is restricted to only people with access

- [x] /processes/environment-variables/ - is restricted to only people with access
- [x] create environment variables - is restricted to only people with access
- [x] edit environment variables (including the editor) - is restricted to only people with access
- [x] delete environment variables - is restricted to only people with access

- [x] /admin/users - is restricted to only people with access
- [x] create users - is restricted to only people with access
- [x] edit users - is restricted to only people with access
- [x] delete users - is restricted to only people with access

- [x] /admin/groups - is restricted to only people with access
- [x] create groups - is restricted to only people with access
- [x] edit groups - is restricted to only people with access
- [x] delete groups - is restricted to only people with access

**Acceptance**

- [x] Redo routes to be explicit
- [x] Add to middleware for managing access
- [x] Update permission seeder to use new gates
- [x] Hide irrelevant nav buttons based on permissions
- [x] New UI for permission tab
- [x] Group edit has permission tab
- [x] Update access denied template to include the nav and default sidebar
- [x] Unit tests that a user is created with different permissions and confirm that they are allowed/denied to the resource
- [x] Unit tests that a user is created with different permissions and then added to a group and that they are allowed/denied to the resource

**Comment by velkymx** [comment]
@milaendo let's use Toggles for the checkboxes on the UI. Make the two states "allow" and "deny"

http://www.bootstraptoggle.com

![screenshot 2019-01-15 10 42 23](https://user-images.githubusercontent.com/535300/51201935-42794580-18b2-11e9-849b-af22f1784fdf.png)

**Comment by ryancooley** [comment]
@velkymx we are ready to close this ticket with the exception of a CircleCI issue we need feedback on.

We also need guidance on if you'd like us to create a pull request now or hold off until #1180 is completed.
