### ISSUE TITLE
Task Reassignment

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1155]
As a user I want to be able to reassign my tasks to other users. 

- [x] Start with a unit test to confirm it all works
- [x] Add a checkbox under the task assignment, "Allow Reassignment"
- [x] If the checkbox is true, then allow the assigned user (and admin) the ability to choose another user from the task detail and then assign the task to them.

If the reassign flag is set, and the assignment is group, only allow reassignment to other members of that group only.

**Comment by caleeli** [comment]
If the assignment is "requestor" shown we show the Reassignment option?
