### ISSUE TITLE
Edit Data

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1175]
As a user I want be able to edit the data set as a process flows. 

For tasks that have not been completed, add a tab that has key / value pairs of the Vue data that can be edited. 

From the Request Summary, if the request is completed,  add a tab that has key / value pairs of the Vue data that can be edited. 

- [x] Add to config UI group / users who can edit data (allow multiple)
- [x] Add tab to task screen that shows the data (maybe JSON with the Script editor?)
- [x] User can edit data of a task ONLY if the task is status "In Progress"
- [x] User can edit data of Request ONLY for requests in status "Completed"
- [x] Unit test that this permission is being respected
- [x] Verify that when an edit happens a comment is generated (event) See #1183

**Comment by caleeli** [comment]
@velkymx how the data should be edited, are we going to use a JSON editor?
Remember that the data could be saved by any previous screen and could contain complex data like arrays of objects, calculated fields, texts, numbers and booleans. Also the scripts and connectors could save data with any json structure.

**Comment by caleeli** [comment]
Request:
![image](https://user-images.githubusercontent.com/8028650/51190953-c3880b00-18b9-11e9-8c50-42b2f2fbd648.png)

Task:
![image](https://user-images.githubusercontent.com/8028650/51192073-25497480-18bc-11e9-9db8-4dbca2241580.png)

**Comment by ryancooley** [comment]
@caleeli As part of ticket #1180, we are now using [Laravel Policies](https://laravel.com/docs/5.7/authorization#creating-policies) to determine user permissions for various models.

In our branch (feature/1180-b), we have created an update method to the Process Request policy. You can access this in several ways.

- From within a controller, you can add `$this->authorize('update', $processRequest);`
- Via the user model, you can check the truth of the statement `$user->can('update', $processRequest)` 
- Via a Blade template, you can use `@can('update', $processRequest)` and its closing tag `@endcan`

If you have any questions, please feel free to ping @milaendo or myself, or we can discuss during the standup.

**Comment by velkymx** [comment]
@caleeli Let's just dump the JSON to the Javascript editor (the one from the scripts area).

**Comment by nolanpro** [comment]
Merged

**Comment by PMQABen** [comment]
✅ Add to config UI group / users who can edit data (allow multiple)
✅ Add tab to task screen that shows the data (maybe JSON with the Script editor?)
✅ User can edit data of a task ONLY if the task is status "In Progress"
✅ User can edit data of Request ONLY for requests in status "Completed"
✅ Verify that when an edit happens a comment is generated

**Comment by velkymx** [comment]
Reopening. This should not have been merged because the requirements.

**Comment by caleeli** [comment]
What requirements?

**Comment by velkymx** [comment]
@caleeli Let's just dump the JSON to the Javascript editor (the one from the scripts area). (this is from above)
