### ISSUE TITLE
Requests Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1188]
1. Your Leave Absence Request is in a new HR category.
2. I then created a new Process for a second category.
3. The Absence Request Process properly displays in the HR category.
4. However, my faux-Process doesn't display in the second category.
5. My faux-Process is active.
6. I assigned "All Permissions" group to both start and cancel Requests (since that is the only option available presently in those drop-downs).

In the screen below you can see that the request is not returned in the Purchasing category

![screenshot 2019-01-15 09 52 14](https://user-images.githubusercontent.com/535300/51199293-3fc72200-18ab-11e9-9596-23b0c9f5bff8.png)

**Comment by nolanpro** [comment]
@velkymx Did the process you create have a start event? I noticed that if you just create a process with no nodes it won't show up in that list, no matter the category.

I seem to remember the modeler use to always have a start event by default but I'm not seeing that any more.
