### ISSUE TITLE
Adding user to group does not update page unless reloaded

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/bpm#1198]
1. Create new group
2. Edit the new group
3. Go to "Group Members"
4. Click +User, select one or more users, press save

**Result:**
The "Group Members" tab does not update to reflect the new user(s) until the page is reloaded, and you navigate back to the "Group Members" tab.

**Expected:**
The "Group Members" tab updates once the save button is pressed, to show the newly added user(s).

**Comment by nolanpro** [comment]
This has been merged. Closing
