### ISSUE TITLE
Archiving Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1209]
When I try to archive a process it should remove it from the process list and move to the archive. Right now it's staying on the active list.

**Comment by ryancooley** [comment]
@velkymx I'm able to reproduce this but only when the process has associated requests. It sets the process to inactive but then returns an error that says "the item should not have associated requests."

So it gets to the inactive state but is not actually archived. Should inactive processes be moved to the archive? Or should we archive the process even if it has associated requests?

**Comment by ryancooley** [comment]
After group discussion it was decided that these should be archived even if there are associated requests, as long as those associated requests can still be completed.
