### ISSUE TITLE
Add generic dots to the Environment Variable "value" field

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/bpm#1222]
I understand that currently we are leaving the Value field blank, as outlined in https://github.com/ProcessMaker/bpm/issues/844 since it could potentially contain passwords or other sensitive information.

Why not just have the field show a generic set of `••••••••` dots, and maybe some sort of helper text saying that the text in this field will always appear masked.

**Comment by milaendo** [comment]
as to not introduce anything new, this ticket will just add a helper text to the value field so the user understand that it has been properly saved. 
![screen shot 2019-01-23 at 3 10 52 pm](https://user-images.githubusercontent.com/29641725/51643428-4c89ec80-1f21-11e9-9fef-33b1f842bcda.png)
