### ISSUE TITLE
Horizon and Echo don't run upon install

### ISSUE THREAD

**Issue by ryancooley** [ProcessMaker/bpm#1277]
This causes many errors related to process requests.

![screen shot 2019-01-28 at 9 49 05 am](https://user-images.githubusercontent.com/867714/51856708-32fff080-22e5-11e9-89bd-a72c654d5a6d.png)

On every page, the call to socket.io is returning a 404 (see network panel in dev tools)

**Comment by Kookster310** [comment]
This is an issue with aws application load balancer capacity.
Currently the QA PM4Build server is only able to have 49 active builds with echo-server and socket.io port listening. After checking the port allocation, it has exceeded that limit.
After discussing with Alan, I will be making the cleanup script much more aggressive, and do port free up on builds that are older than 24 hours.

**Comment by nolanpro** [comment]
@Kookster310 Oh we were actually seeing this problem locally with homestead/vagrant. If you follow the setup instructions in "Steps for Development Installation" on the readme you should see the problem

**Comment by velkymx** [comment]
@Kookster310 any updates on this?

**Comment by nolanpro** [comment]
@ryancooley I tried this after destroying and rebuilding the vagrant box and it seems to all be working correctly (after docker installs, which is a separate issue I filed in the google form). Could you try again and see if it's still an issue?

**Comment by velkymx** [comment]
We'll revisit if this starts happening again.
