### ISSUE TITLE
Cannot edit a File Upload control when it is inside a multi-column control

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/bpm#1288]
Create a new form screen
Drag over a multi-column control into the form
Drag over a file upload control into any of the two columns

**Result:**
![image](https://user-images.githubusercontent.com/28575916/51870874-ae739900-2309-11e9-9739-95d1a3f2fd4a.png)

**Comment by marcoAntonioNina** [comment]
Solved in the current version.
