### ISSUE TITLE
Screen Builder CSS

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1313]
Track as part of the issue in the form builder: https://github.com/ProcessMaker/vue-form-builder/issues/46

- [x] Add the custom css property from vue-form-builder
- [x] Save the custom css configuration
- [x] Add the custom css property to the process runtime
- [ ] New release of vue-form-builder and update in package.json

**Comment by velkymx** [comment]
Scoped to the form specific.
Add to the grey menu and show a modal with the editor

**Comment by caleeli** [comment]
Added the custom css property from vue-form-builder
![image](https://user-images.githubusercontent.com/8028650/52347865-561f5400-29f9-11e9-8c32-0b7f1694ba24.png)

Used in process runtime:
![image](https://user-images.githubusercontent.com/8028650/52347894-6800f700-29f9-11e9-957b-74142e4aedb7.png)

Saved on database.

**Comment by velkymx** [comment]
@caleeli @nolanpro can I access individual elements using their ID (ex: #start_date { })?

**Comment by velkymx** [comment]
@PMQABen can you run this through QA?

**Comment by tdondich** [comment]
Does this custom CSS impact the rest of the page?  Is it scoped?

Also, to @velkymx 's note, we should add custom attributse to the rendered element if not already provided, such as form-name="customer.orders".  ID selectors will not be correct since periods are allowed in the form element name (for sub properties).

**Comment by tdondich** [comment]
If it's NOT scoped, it needs to become scoped.  Use a JS library to make it scoped, if needed.

**Comment by nolanpro** [comment]
@tdondich its scoped in pure css. I wrapped the renderer in a div called #renderer-container and prefixed all custom css declarations with that div name.

If the user enters
`div { color: Red }; .col-sm { font-size: 20px; }`
it renders the style sheet as
`div#renderer-container div { color: Red }; div#renderer-container .col-sm { font-size: 20px; }`

I couldn't find any wrappers or js libraries that didn't break vue reactivity (needed for calculated fields). I tried shadow dom, vue-custom-element, and web components.

**Comment by caleeli** [comment]
Yes, but it seems that it could not cover all the rules properly, the style generated for the css that Ben used was the following:

```
<style data-v-1990bbbc="">
@import url(https://fonts.googleapis.com/css?family=Pacifico);
@import url('https://fonts.googleapis.com/css?family=Anton');

h1,h2{
  text-align:center;
}

h1{
  color:rgba(100, 50, 255, .8);
  font-family: 'Pacifico', cursive;
  color:#212121;
}
.rainbow {
  
   /* Font options */
  font-family: 'Pacifico', cursive;
  text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
  font-size:40px;
  
   /* Chrome, Safari, Opera */
  -webkit-animation: rainbow 3s infinite; 
  
  /* Internet Explorer */
  -ms-animation: rainbow 3s infinite;
  
  /* Standar Syntax */
  animation: rainbow 3s infinite; 
}

/* Chrome, Safari, Opera */
@-webkit-keyframes rainbow{
div#renderer-container   0%{color: orange;} 	
div#renderer-container   10%{color: purple;} 	
div#renderer-container 	20%{color: red;} 
div#renderer-container   30%{color: CadetBlue;} 
div#renderer-container 	40%{color: yellow;} 
div#renderer-container   50%{color: coral;} 
div#renderer-container 	60%{color: green;} 
div#renderer-container   70%{color: cyan;} 
div#renderer-container   80%{color: DeepPink;} 
div#renderer-container   90%{color: DodgerBlue;} 
div#renderer-container 	100%{color: orange;} 
}

/* Internet Explorer */
@-ms-keyframes rainbow{
div#renderer-container   0%{color: orange;} 	
div#renderer-container   10%{color: purple;} 	
div#renderer-container 	20%{color: red;} 
div#renderer-container 	40%{color: yellow;} 
div#renderer-container 	60%{color: green;} 
div#renderer-container 	100%{color: orange;} 
}

/* Standar Syntax */
@keyframes rainbow{
div#renderer-container   0%{color: orange;} 	
div#renderer-container   10%{color: purple;} 	
div#renderer-container 	20%{color: red;} 
div#renderer-container 	40%{color: yellow;} 
div#renderer-container 	60%{color: green;} 
div#renderer-container 	100%{color: orange;} 
}

body{
  background-color:#607D8B;
}

.container{
  background-color:#E0F2F1;
  padding:10px;
  border:2px solid black;
  border-radius:15px;
}
</style>
```

**Comment by PMQABen** [comment]
Change this:
```
h1{
  color:rgba(100, 50, 255, .8);
```

To this:
```
div{
  color:rgba(100, 50, 255, .8);
```
And it'll affect the whole form. 😄

**Comment by nolanpro** [comment]
@PMQABen @caleeli yeah we shouldn't be allowing `@import` either. I'll fix that
