### ISSUE TITLE
Edit Data Permissions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1340]
I want to add a permission to allow an individual or group to edit data (task and request levels separate please)

**Comment by ryancooley** [comment]
@velkymx Quick UI question: in a task request, we are using tabs to switch between the form and the data editor. When a user does not have data permissions, there is only one tab. Should we just remove the tab bar entirely in that case?

**Currently: Task Edit with Both Tabs**
![screen shot 2019-02-11 at 10 49 53 am](https://user-images.githubusercontent.com/867714/52593019-c57fb400-2dfc-11e9-9db1-439d151dc958.png)

**Option A: Task Edit with One Tab**
![screen shot 2019-02-11 at 10 50 22 am](https://user-images.githubusercontent.com/867714/52593020-c57fb400-2dfc-11e9-993b-f62b6c89a00e.png)

**Option B: Task Edit with No Tabs**
![screen shot 2019-02-11 at 1 01 40 pm](https://user-images.githubusercontent.com/867714/52593224-42ab2900-2dfd-11e9-9726-50bb59587f26.png)

**Comment by velkymx** [comment]
Yes. Remove it
