### ISSUE TITLE
Swagger Execute throwing 500

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1354]
![screenshot 2019-02-12 13 31 39](https://user-images.githubusercontent.com/535300/52669307-99caff80-2eca-11e9-9a3e-dd2317fc11a8.png)

**Comment by velkymx** [comment]
Go to the swagger doc, expand the api element, and click execute.

**Comment by milaendo** [comment]
I was unable to reproduce this error

![screen shot 2019-02-19 at 12 25 42 pm](https://user-images.githubusercontent.com/29641725/53045046-7f9c9e80-3441-11e9-8fbf-ba64b4107b6c.png)

**Comment by velkymx** [comment]
Fixed already. Could be a server issue.
