### ISSUE TITLE
HTML code not being stripped from screen builder

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/bpm#1358]
1. Create a new Display Screen
2. Add a Text Control
3. Add any text into the "Text Label" field, style it with HTML
4. Save the form, reload the page

**Result:**
HTML code is stripped from the text label.
[Untitled-480.mp4.zip](https://github.com/ProcessMaker/bpm/files/2862342/Untitled-480.mp4.zip)

It's expected that Screen Builder CSS will eventually allow users to customize text labels and other parts of the form, but we might want to prevent HTML tags from displaying/formatting on the screen, so they don't make customers think they can use HTML codes.

**Comment by velkymx** [comment]
This will be resolved as part of #1348
