### ISSUE TITLE
Installer Migrates without Access

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1362]
I was able to complete the installer even though the MySQL user didn't have access. Can we trap for this (test the connection) as part of the installer

**Comment by nolanpro** [comment]
Tried this and the installer fails when the user doesn't have access. It does not write the .env file. Is there another place it was failing? 
![image](https://user-images.githubusercontent.com/2546850/53137036-12b70080-3536-11e9-98f6-9e15e7c84e0a.png)

**Comment by velkymx** [comment]
This is another example of a bad experience installing. We need to test the connection before allowing the installer to continue.
