### ISSUE TITLE
Queue Calling Bad Assets

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1364]
Some process in the queue is calling front end files. For example, a file that does not exist: /js/lib.esm.js.map throws 404 (but fails instead with 500 because user does not exist, also separate bug). I don't think the queue should be trying to get front end assets

Start a new process and look at the logs in storage. Shows "Call to a member function topMenu() on null" because the user does not exist

**Comment by milaendo** [comment]
I was also not able to reproduce this error. 

![screen shot 2019-02-19 at 12 30 19 pm](https://user-images.githubusercontent.com/29641725/53045309-22edb380-3442-11e9-920d-4d3f2b957334.png)

**Comment by velkymx** [comment]
@nolanpro can you elaborate on this issue?

**Comment by milaendo** [comment]
Cant reproduce

**Comment by velkymx** [comment]
If this crops up again we'll reopen this issue.
