### ISSUE TITLE
Request Log Dates

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1367]
When you look at the list of changes in a request in the bottom log the dates are all the same and no using the date of the notification.

**Comment by milaendo** [comment]
@velkymx the dates seem to be working as intended. I may not be properly understanding the ticket.
![screen shot 2019-02-19 at 9 27 26 am](https://user-images.githubusercontent.com/29641725/53034698-9aaee480-3428-11e9-94fe-65a29fbf1b96.png)

**Comment by velkymx** [comment]
@milaendo if you open a request and then at ticket, edit the request data and then complete the task you will see the bug.

**Comment by milaendo** [comment]
I either need more detailed steps to reproduce or this is just not a bug I can reproduce. @PMQABen are you able to provide more info on this ticket?

![screen shot 2019-02-19 at 10 52 14 am](https://user-images.githubusercontent.com/29641725/53039683-88d33e80-3434-11e9-9c1a-3e3f82e32fbb.png)

**Comment by PMQABen** [comment]
1. Create new request
2. Fill out request
3. Edit & save request data
4. Complete the request

Those are the steps I followed, but I cannot reproduce. What I did notice, was I tried multiple times to edit and save the request data, but the data never updated. The log says it was edited though.

**Comment by velkymx** [comment]
@milaendo you can see the issue happening in the log data.

![screenshot 2019-02-19 13 39 40](https://user-images.githubusercontent.com/535300/53049405-db6c2500-344b-11e9-9d27-4915b255c185.png)

**Comment by velkymx** [comment]
It's like the log is being created all at the same time and using the timestamp of the request change.

**Comment by milaendo** [comment]
thats just the time that I updated it. It only took me a minute to accomplish everything there. Should these be different?

**Comment by PMQABen** [comment]
That can also happen if someone is rushing through the process. Should the log be displaying the seconds as well as the hour/minute?

**Comment by velkymx** [comment]
I'm always seeing the same date and time when I edit the data and then save it.

**Comment by velkymx** [comment]
Well try this... give it a few minutes between editing and saving and see if it changes.

**Comment by milaendo** [comment]
in the screen shot above you can see I tried that. and it shows one edit at 10:49 and the other at 10:50, isnt that intended behavior?

**Comment by velkymx** [comment]
I believe the bug is that it is using the data of the task when saving the edit change, not the timestamp of the change itself. If it's all happening as part of a single save, then that could be the issue.

**Comment by PMQABen** [comment]
![image](https://user-images.githubusercontent.com/28575916/53049889-e6738500-344c-11e9-9143-cfb4f45ec3e0.png)
This is what I came up with, working through a process request with a one minute pause between steps and editing data.

**Comment by velkymx** [comment]
Why isn't it showing that admin admin has edited the **_task_** data?

**Comment by milaendo** [comment]
there isnt really a difference between task data and request data in the system. Is there maybe a different ticket we should open for the issue you are bringing up?

**Comment by velkymx** [comment]
Yes there is. One is editing from a task and the other in a request. This is mostly about an audit log.
