### ISSUE TITLE
Group Seeders

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1373]
Update the installer and group permission seeders.

- [x] Pre-loaded groups are: Requesters, Process Designers and Administrators
- [x] These pre-defined groups should be installed only if the user allows this on the installation process.

The following permission structure needs to be defined:

- [x] Requesters

- View All Request
- View Users
- View Groups
- View Comments
- Create Comments
- Edit Comments

- [x] Process Designers

- View All Requests
- View All Processes
- Create Processes
- Edit Processes
- Archive Processes
- View Categories
- Create Categories
- Edit Categories
- Delete Categories
- View Screens
- Create Screens
- Edit Screens
- Delete Screens
- View Scripts
- Create Scripts
- Edit Scripts
- Delete Scripts
- View Environment Variables
- View Users
- View Groups

- [x] Administrators

- View Users
- Create Users
- Edit Users
- Delete Users
- View Groups
- Create Groups
- Edit Groups
- Delete Groups
- View Auth Clients
- Create Auth Clients
- Edit Auth Clients
- Delete Auth Clients
- Delete Comments

**Comment by ryancooley** [comment]
@velkymx Do we want to keep the default "Users" and "All Permissions" groups? I'd recommend removing them as they add more clutter and confusion to the Groups page.

**Comment by velkymx** [comment]
@ryancooley yes. Remove them.
