### ISSUE TITLE
Update Seeders

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1377]
Update the seeders to use updated data. The current seeder is for a VERY old process and needs to be replaced with a new one with new updated assets built with the latest tools.

**Comment by velkymx** [comment]
@nolanpro We talked about replacing the seeder entirely with a new process and updated data.

**Comment by nolanpro** [comment]
@velkymx a lot of the seeds are going to change with the new modeler version. Should we wait on this until thats in?

**Comment by velkymx** [comment]
We've removed this seeder. We'll add a new one in a more organized fashion.
