### ISSUE TITLE
Edit Auth Validation Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1390]
In the "Edit Auth Client" screen, one can remove the "Name" and "Redirect URL" values and then click "Save". The screen is not dismissed, but from the "Auth Clients" page I can see that the "Name" field loses its value. When I click the "Close" button, the "Redirect URL" has no value. (Clicking the "Close" button is the only way to dismiss the screen because the "Save" button doesn't dismiss the screen when all three fields don't have values.)

**Comment by milaendo** [comment]
I was not able to reproduce this.

![screen shot 2019-02-19 at 12 17 05 pm](https://user-images.githubusercontent.com/29641725/53044588-4dd70800-3440-11e9-8a5f-c6eb42c5ab65.png)

**Comment by velkymx** [comment]
This looks fixed in the latest branch. Closing.
