### ISSUE TITLE
Build Modeller for NPM

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1399]

**Comment by nolanpro** [comment]
@caleeli I tried it out with https://github.com/ProcessMaker/modeler/pull/243 and it seems to work fine without the laravel-mix/babel update. It just needs the new validation-status component in resources/js/processes/modeler/components/ModelerApp.vue

**Comment by chipit24** [comment]
I've updated https://github.com/ProcessMaker/modeler/pull/243, and have created PR https://github.com/ProcessMaker/bpm/pull/1408 to update `ModelerApp.vue`.
