### ISSUE TITLE
UI changes for group membership config inside /admin/users

### ISSUE THREAD

**Issue by PMQABen** [ProcessMaker/bpm#1403]
1. Log into `/admin/users`
2. Edit a user
3. Go to the Groups tab
4. Click `+Add User to Group`

![image](https://user-images.githubusercontent.com/28575916/53121916-26e50880-350a-11e9-95e1-d78e9931fa39.png)
Buttons need to use the correct class formatting, the header text of the modal should be in black as opposed to blue.

----

![image](https://user-images.githubusercontent.com/28575916/53124225-acb78280-350f-11e9-9144-5d322a6dc63f.png)
Buttons need to use the correct class formatting. Message needs to be rewritten:
`Are you sure you want to remove the user from the group !!GROUPNAME!!?`

----

1. Log into `/admin/users`
2. Edit a user
3. Go to the Groups tab
4. Click `+Add User to Group`
5. Do not choose a group, press OK

**Result:** Nothing happens. No error message is thrown on screen or in the console, but the modal remains displayed.

----

![image](https://user-images.githubusercontent.com/28575916/53123816-cad0b300-350e-11e9-962e-93f48b597d54.png)
Can we move the modal further down the page? It would prevent stuff like this from occurring:
![image](https://user-images.githubusercontent.com/28575916/53123866-f3f14380-350e-11e9-8fb9-2270389921be.png)

----

One last potential change, why does the drop-down menu show groups the user is already in? If a user is in a group called "foobar", I probably should not see "foobar" as a selectable choice if I'm adding them to a new group.

**Comment by velkymx** [comment]
@PMQABen are you using the latest version of PM4? We've updated all modals.

**Comment by velkymx** [comment]
https://develop.bpm4.qa.processmaker.net

**Comment by velkymx** [comment]
Yep. Confirmed. WHO ADDED THIS?
