### ISSUE TITLE
Super Admin Permissions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1409]
If you check that the account is a super user, it isn't reflected in the UI on revisiting the page. Either the setting isn't being saved OR the ui is not updating properly.

route: /admin/users/ID/edit

video: https://www.dropbox.com/s/28kzxa2w1dtfh5r/Super%20User%20Bug.mov?dl=0

**Comment by nolanpro** [comment]
I wasn't able to reproduce on local or dev develop.bpm4.qa. Is this what you are referring to? Also if I un-super-user the admin user and remove them from the all permissions group, they can't do anything as expected.
![reproduce](https://user-images.githubusercontent.com/2546850/53187859-dc6e9500-35b8-11e9-8f73-b69777b20689.gif)

**Comment by velkymx** [comment]
I WAS able to reproduce locally and on the demo server.

**Comment by milaendo** [comment]
@velkymx I was not able to reproduce this error. Is this on the demo branch or a different one?

**Comment by milaendo** [comment]
@velkymx we finally found the issue! the saml plug-in needs to make the usernames are alpha-dash.

**Comment by caleeli** [comment]
Yes, the username may only contain letters, numbers, and dashes.

**Comment by milaendo** [comment]
@caleeli Thank you for confirming, so then this bug is being caused by the plugin team. @velkymx

**Comment by Cievoloth** [comment]
@milaendo  thanks for the information, we will correct the username creation in our plugin. 
@MiltonPM please proceed with the change. 

Thanks
