### ISSUE TITLE
NPM Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1417]
Unexpected string in JSON at position 223725 while parsing '{
npm ERR!   "requires": true,
npm ERR!   "lockfileVersion'

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'ci' ]
2 info using npm@6.7.0
3 info using node@v10.0.0
4 verbose npm-session b103bd81af6c0eb2
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /Users/alanbollinger/dev/bpm
8 verbose teardown shutting down workers.
9 info teardown Done in 0.001s
10 verbose stack SyntaxError: Unexpected string in JSON at position 223725
10 verbose stack     at JSON.parse (<anonymous>)
10 verbose stack     at readFileAsync.then.str (/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js:436:23)
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
10 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
10 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
11 verbose cwd /Users/alanbollinger/dev/bpm
12 verbose Darwin 18.2.0
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "ci"
14 verbose node v10.0.0
15 verbose npm  v6.7.0
16 error Unexpected string in JSON at position 223725
17 verbose exit [ 1, true ]

**Comment by chipit24** [comment]
There’s a missing comma in the lockfile at line 6074: https://github.com/ProcessMaker/bpm/blob/develop/package-lock.json#L6074. The comma can be re-added, or the lockfile can be removed and regenerated:
```
rm package-lock.json
npm i --package-lock-only
```

The offending commit was https://github.com/ProcessMaker/bpm/commit/a44317c3f9e692368bb07cbf6e3e82544629efbd, according to git blame.

**Comment by velkymx** [comment]
Fixed. Thanks @chipit24
