### ISSUE TITLE
Update Translation File

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1471]
Make sure the translation file has all of the keys we're using throughout the code base. Test by inserting an different language file (chinese maybe?) and check that the entire site translates properly. 

- [x] Add any missing translations to language file
- [ ] Add tests to confirm working
- [x] Note any places where there are not translations

**Comment by milaendo** [comment]
There is currently no translation in the queue manager.
Non-standard translation in the auth as well as reset password flow.
task edit screen dates "due on" "completed on" 
Modeler and screen builder
confirmation modal buttons
env vars delete alert 
delete api token modal
