### ISSUE TITLE
Task Menu

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#148]
![image](https://user-images.githubusercontent.com/535300/40246280-1299ce50-5a7d-11e8-8fe5-55def51b3f56.png)
[icomoon (1).zip](https://github.com/ProcessMaker/bpm/files/2017666/icomoon.1.zip)

Requests and Tasks are now split into 2 separate menus. 

Here are the left nav menu titles + icons needed for Tasks. You've already created the first 3 of them :)

- Assigned
- Unassigned 
- Completed
- Paused 

Please update the current left navigation with the above text and attached icons.

Please create —

- Expanded version with text
- Collapsed version without text

Ref:https://processmaker.atlassian.net/browse/PMUI-135

**Comment by velkymx** [comment]
Upon review... it appears the icons have gone missing. Correct layout below.

![screenshot 2018-06-13 09 35 33](https://user-images.githubusercontent.com/535300/41365039-2cb0c08a-6eed-11e8-9cb5-3dfe3294eb81.png)

**Comment by milaendo** [comment]
![screen shot 2018-06-13 at 1 43 50 pm](https://user-images.githubusercontent.com/29641725/41377079-d4671f50-6f0f-11e8-86bd-c26a7f819546.png)
icomoon icons are super tiny

**Comment by milaendo** [comment]
![screen shot 2018-06-13 at 2 01 39 pm](https://user-images.githubusercontent.com/29641725/41377930-72b35014-6f12-11e8-8d81-cb1c935aebc3.png)

**Comment by milaendo** [comment]
![screen shot 2018-06-13 at 3 08 00 pm](https://user-images.githubusercontent.com/29641725/41381239-e825b3ec-6f1b-11e8-8972-d6d9a62308ca.png)

**Comment by velkymx** [comment]
Try these icons.

[icomoon.zip](https://github.com/ProcessMaker/bpm/files/2112107/icomoon.zip)

**Comment by milaendo** [comment]
this is the same zip as previously used

**Comment by velkymx** [comment]
#shocked ok I'll follow up on the newer ones.

**Comment by velkymx** [comment]
Updated fonts

[fonts-20180618.zip](https://github.com/ProcessMaker/bpm/files/2113303/fonts-20180618.zip)
