### ISSUE TITLE
Logging Inconstant

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1480]
Note the screenshot. Sometimes the message has quotes, some times not. Can we keep it consistent and use what was there? Why did we introduce quotes?

![image](https://user-images.githubusercontent.com/535300/53900992-ab4b8700-3ff2-11e9-9e73-2b7a9d0f188c.png)

**Comment by caleeli** [comment]
@velkymx how do you generate that log? Could you share the process or the how to reproduce it.
I could not find that message quotes message.
