### ISSUE TITLE
Update swagger annotations for models and controllers

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/bpm#1492]
This can be done in branch feature/1472 where I have already updated User and ProcessRequest models and *some* of their controller methods. See some the changes I made here: https://github.com/ProcessMaker/bpm/commit/5d5b47201d11c33b3199d970f49536591e691396

Since working with these swagger (aka openAPI) annotations can be kind of a learning curve, let's start with these that I think are most important. If a public function in the controller is not annotated, it should be added. If it is annotated, it should be verified and updated. For controllers, only annotate endpoints listed in routes/api.php

In ProcessMaker/Http/Controllers/Api/ and their associated models in ProcessMaker/Models

- [x] ProcessController
- [x] ProcessCategoryController
- [x] ProcessRequestController
- [x] TaskController (model for this is ProcessRequestToken.php)
- [x] UserController
- [x] GroupsController
- [x] GroupMemberController

- Make sure summary, operationId, and tags are correct. Operation ID can be anything that makes sense as a method call.

- Try to pay attention to important query string parameters we use in the controller function. For example '?event=node_1'. Look for `$request->input` and `$request->get` in the method you are annotating. Not all properties need to be annotated. For example, "include" and most filters that can match multiple columns doesn't need to be annotated yet. Most post and puts will just reference the model schema.

- Most models were annotated incorrectly. They should be in this format where, in the main schema, the ref to editable schema, and its non-editable properties, are completely wrapped in `allOf={`:
```
 * @OA\Schema(
 *   schema="processRequestEditable",
 *   @OA\Property(property="user_id", type="string", format="id"),
 *   @OA\Property(property="callable_id", type="string", format="id"),
 *   @OA\Property(property="data", type="string", format="json"),
 *   @OA\Property(property="status", type="string", enum={"DRAFT", "ACTIVE", "COMPLETED"}),
 * ),
 * @OA\Schema(
 *   schema="processRequest",
 *   allOf={
 *       @OA\Schema(ref="#/components/schemas/processRequestEditable"),
 *       @OA\Schema(
 *           type="object",
 *           @OA\Property(property="id", type="string", format="id"),
 *           @OA\Property(property="process_id", type="string", format="id"),
 *           @OA\Property(property="process_collaboration_id", type="string", format="id"),
 *           @OA\Property(property="participant_id", type="string", format="id"),
 *           @OA\Property(property="process_category_id", type="string", format="id"),
 *           @OA\Property(property="created_at", type="string", format="date-time"),
 *           @OA\Property(property="updated_at", type="string", format="date-time"),
 *      )
 *   },
 * )
```
- In controllers, the properties in path need to be in curly braces and must match the OA\Parameter name. These are missing or not named right in several places.
For example:
```
     *  @OA\Get(
     *     path="/users/{user_id}",
      ...
     *     @OA\Parameter(
     *         description="ID of user to return",
     *         in="path",
     *         name="user_id",
      ...
```

- In your .env, add `APP_DEBUG=TRUE` and `L5_SWAGGER_GENERATE_ALWAYS=TRUE` so the swagger json is generated on every reload.
- After you make changes, reload bpm4.local.processmaker.com/api/documentation. If you don't see any errors, open the function you worked on and use the "try it out" function to make sure everything works as expected. Also make sure the "Example Value" has all the expected properties. Editable should only have the ones defined in the model has editable, while the main schema should have them all.
- If an error appears, it's usually a missing comma or a parentheses in the annotations.
- Try to indent correctly

Some examples here: https://github.com/zircote/swagger-php/tree/master/Examples/petstore-3.0

**Comment by milaendo** [comment]
The following endpoints need to be annotated:
startProcesses, 
process(import),
