### ISSUE TITLE
Docker Fails: permission denied

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1506]
When running a script, a request will break (ending in error) `WARNING: Error loading config file: /root/.docker/config.json: stat /root/.docker/config.json: permission denied`

Let me know if we need to fix this in the main code base or if this is a server issue

**Comment by josemaldonad0** [comment]
FWIW, this error will show AFTER the script has (successfully) run.

**Comment by Kookster310** [comment]
We believe to have found the issue to why it wasn't always looking in .env.
It seems that there were some queue workers being run in parallel from an older build design.
I have removed these workers, config files, and removed them spawning from future circleci deployments. Going to keep an eye on to make sure there are no more failures with this error.
