### ISSUE TITLE
Top navigation is incorrectly vertically aligned

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#1517]
The top main navigation is incorrectly vertically aligned.  Please correct without using margins/padding.  This should utilize flexbox for proper alignment.

![Annotation 2019-03-12 094236](https://user-images.githubusercontent.com/3330334/54218734-5a80d600-44ab-11e9-9bf6-f9feb94adbf0.jpg)

**Comment by milaendo** [comment]
@velkymx are you ok with this being resolved in #1518?
