### ISSUE TITLE
Add node script executor

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/bpm#1547]
This will add the node script executor from this repo: https://github.com/ProcessMaker/pm4-docker-executor-node

- [x] Wire up the executor
- [x] Move some sdk build options to config/script-runners.php. Different generators require different options (like invokerPackage can not be present for node but must be present for php)

**Comment by velkymx** [comment]
- [ ] Update the tests to include Node
- [ ] Document the issues with Node for documentation

**Comment by nolanpro** [comment]
Tests can not include node until the executor is published to dockerhub. Waiting on the automated build server, then adding the tests here should be simple
