### ISSUE TITLE
Updated Screen Builder Text

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1592]
In Screens Builder, change the message for a Record List control that displays in Preview when the "Record Form" setting references its own page. Presently it reads: "The add/edit form referencing our own form which is not allowed." Change it to something written in better English, such as: "The Record List control is not allowed to reference other controls on its own page to add or edit records. Specify a secondary page with controls to enter records."

In the Record List control, change in Screens Builder "List Name" and "List Label" setting labels. Change them to "Field Name" and "Field Label" (respectively) to be consistent with other setting labels in Screens Builder.

Capitalize the word "widths" in the setting label "Column widths" to match Title case as in the "Options List" settings that use a similar GUI.

Change the instructional text below the "Radio Group" control options list for ProcessMaker Screens. Note that this message was copied from the "Select" control options list instructional text. Change the instructional text from "List of options available in the select drop down" to "List of options available in the radio button group".

**Comment by milaendo** [comment]
closing this to move it to the form-builder repo. https://github.com/ProcessMaker/vue-form-builder/issues/129
