### ISSUE TITLE
BPMN Upload Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#1599]
In the designer I cannot upload the BPMN file into a new process.

**Comment by velkymx** [comment]
When I'm in the modeler and I click to upload a valid BPMN file - currently it shows a pop-up modal and let's me browse for the file. Then nothing. #fail

**Comment by milaendo** [comment]
I did a bit of digging into this issue, it looks like we just copied over the same function from the modeler but its not actually doing anything. @caleeli I think you might need to take this over.

**Comment by chipit24** [comment]
Fixed in https://github.com/ProcessMaker/bpm/pull/1614.
