### ISSUE TITLE
Create Input Document

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#182]
Create the modal with the form.

Web link: https://zpl.io/VYAy7Nk

<img width="364" alt="screen shot 2018-06-01 at 3 24 17 pm" src="https://user-images.githubusercontent.com/39599643/40865958-033516de-65b0-11e8-8609-1d0457563854.png">

**Text:** 

Document Type:
- Digital
- Printed
- Digital/ Printed

Enable Versioning:
- Yes
- No

Unit:
- Kb
- Mb

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/249
