### ISSUE TITLE
Create Trigger Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#183]
Create form in modal.

<img width="397" alt="screen shot 2018-05-31 at 5 25 12 pm" src="https://user-images.githubusercontent.com/39599643/40814863-a2be65fc-64f7-11e8-817f-79f0316dd9f6.png">

Web link: https://zpl.io/aNpqM7Z

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/247
