### ISSUE TITLE
Create Report Table

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#184]
This is modal window in the designer. NOTE the column builder is going to take more effort.

**Text:**
- Under Type dropdown --- Global, Grid 
- DB Connection - Workflow (doesn't need a drop-down bc there's only 1 option)

**Report table field headings should be:** FORM FIELD | NAME | LABEL | TYPE | SIZE | AUTO INCREMENT | INDEX

<img width="705" alt="screen shot 2018-06-08 at 2 28 51 pm" src="https://user-images.githubusercontent.com/39599643/41181892-5b3e53c2-6b28-11e8-80c0-8e4054784ed0.png">

Web link: https://zpl.io/adMDGjL

**Comment by milaendo** [comment]
does everyone agree on this lib for the bottom half?
https://github.com/SortableJS/Vue.Draggable

**Comment by milaendo** [comment]
Taylor would like to discuss this table more in-depth. The search field, add button and title has been removed see below.

![screen shot 2018-06-12 at 3 39 34 pm](https://user-images.githubusercontent.com/29641725/41321029-f2dcb422-6e56-11e8-82d6-47153ea657ea.png)

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/284
