### ISSUE TITLE
Create Database Connection Form

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#185]
Create a modal with options for database connections.

Web link: https://zpl.io/anmPENr

<img width="372" alt="screen shot 2018-06-01 at 3 28 29 pm" src="https://user-images.githubusercontent.com/39599643/40866038-80175888-65b0-11e8-9c87-51691469f487.png">

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/251
