### ISSUE TITLE
Create Public File Form

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#187]
Create a modal for public files. 

Web link: https://zpl.io/bWRr09M

<img width="504" alt="screen shot 2018-05-31 at 5 08 31 pm" src="https://user-images.githubusercontent.com/39599643/40814468-4da52c38-64f5-11e8-9a49-c89e3cbbd5b0.png">

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/227
