### ISSUE TITLE
API Failure Dialogue 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#205]
When there is an API failure, we need a clean way to show that there was an issue in the UI.

https://zpl.io/29Z4nzz

<img width="913" alt="screen shot 2018-06-11 at 12 49 59 pm" src="https://user-images.githubusercontent.com/39599643/41264346-0c1c8a86-6da1-11e8-8dbb-011b6de96a3c.png">

**Comment by meadrat** [comment]
I assigned this to Jayanta and will keep you posted on completion time.

**Comment by meadrat** [comment]
@velkymx this is ready for dev

**Comment by velkymx** [comment]
![gears](https://user-images.githubusercontent.com/535300/41319574-1a1f7a0c-6e51-11e8-9826-5910d8db7bf6.png)

**Comment by KillahDillah** [comment]
https://github.com/ProcessMaker/bpm/pull/299
