### ISSUE TITLE
JointJS Shapes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#207]
Make the current functionality of drag and drop shapes in to the designer with the crown.

**Comment by velkymx** [comment]
@hjonathan Please update what is completed and what is left to do on this ticket so I can reschedule for next week's sprint.

**Comment by velkymx** [comment]
@hjonathan I've merged the current progress (awesome). We need to talk about what's left to bring it up to parity with the other version.

**Comment by hjonathan** [comment]
This ticket have the next features:
- Drawing of shapes (StartEvent, EndEvent, TaskSshapes) from toolbar
- Drag and Drop of shapes in svg canvas
- Drawing of crown
- Background Grid in svg canvas

**Comment by velkymx** [comment]
There are tickets for all of these. Thanks guys!
