### ISSUE TITLE
Process Designer - Left Nav Bar 

### ISSUE THREAD

**Issue by meadrat** [ProcessMaker/bpm#208]
When the user is working in the designer (Processes) there won't be any icons on the blue left nav bar. 

Please delete the Admin icons. 

Web link: https://zpl.io/blm4xzv

<img width="75" alt="screen shot 2018-06-01 at 1 20 01 pm" src="https://user-images.githubusercontent.com/39599643/40863161-b6038c3a-65a3-11e8-8a3c-bb4d8d806f28.png">

**Comment by velkymx** [comment]
Keep the menus closed when there aren't any menu items.

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/273
