### ISSUE TITLE
Top Nav - Blue Title

### ISSUE THREAD

**Issue by meadrat** [ProcessMaker/bpm#209]
When the user is working in a section of the app, the title of that section (Processes) should be blue. 

Web link: https://zpl.io/blm4xzv

<img width="400" alt="screen shot 2018-06-01 at 1 19 58 pm" src="https://user-images.githubusercontent.com/39599643/40863323-38df5c24-65a4-11e8-865d-f73762de42ff.png">

**Comment by velkymx** [comment]
This requires adding the "active" class to the correct area.
