### ISSUE TITLE
Custom 404

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#211]
When a user access a route that doesn't exist we need to show a custom 404 page.

Current page: 

<img width="1018" alt="screenshot 2018-06-01 14 40 47" src="https://user-images.githubusercontent.com/535300/40864722-d5384ae0-65a9-11e8-869e-62551e803575.png">

**Comment by meadrat** [comment]
I assigned this to Jayanta and will keep you posted on completion time.

**Comment by meadrat** [comment]
@velkymx this is ready for dev. Text is Oops! The page you're looking for could not be found. https://zpl.io/V1qJDpJ
<img width="913" alt="screen shot 2018-06-11 at 12 52 02 pm" src="https://user-images.githubusercontent.com/39599643/41253818-5f9128d2-6d76-11e8-8ce2-e20a21d9a25f.png">

**Comment by velkymx** [comment]
See https://github.com/ProcessMaker/bpm/issues/289
