### ISSUE TITLE
Get Correct Logos

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#225]
Logos colors are wrong and the image are pixelated.

**Comment by velkymx** [comment]
@meadrat can you attach the correct logos?

**Comment by meadrat** [comment]
@velkymx here's a [link](https://drive.google.com/drive/folders/1GRVs4zTiDKLjcdIUUbeshjee5mCKFRam?usp=sharing) to PNG files- lmk if you need anything else for this.

**Comment by velkymx** [comment]
![horizontal-blue](https://user-images.githubusercontent.com/535300/41053247-df99d6ce-696f-11e8-8ffe-15707dbbe3d0.png)
![horizontal-blue 2x](https://user-images.githubusercontent.com/535300/41053248-dfbc1cca-696f-11e8-884e-60cc3d29e307.png)
![horizontal-blue 3x](https://user-images.githubusercontent.com/535300/41053249-dfd4f31c-696f-11e8-814e-387a751364a2.png)
![horizontal-white](https://user-images.githubusercontent.com/535300/41053250-dff1b114-696f-11e8-9f30-970da082115a.png)
![horizontal-white 2x](https://user-images.githubusercontent.com/535300/41053251-e00b32d8-696f-11e8-9902-f20d18b40fd9.png)
![horizontal-white 3x](https://user-images.githubusercontent.com/535300/41053252-e035fe28-696f-11e8-8316-07bd3653d84a.png)
![horizontal](https://user-images.githubusercontent.com/535300/41053253-e0517144-696f-11e8-9d6f-4878ee177412.png)
![horizontal 2x](https://user-images.githubusercontent.com/535300/41053254-e06a42d2-696f-11e8-9398-b0a2e6bda6c4.png)
![horizontal 3x](https://user-images.githubusercontent.com/535300/41053255-e08555fe-696f-11e8-954f-6b79e3772be5.png)
![icon](https://user-images.githubusercontent.com/535300/41053258-e09ec6b0-696f-11e8-9399-cd75edc8754d.png)
![icon 2x](https://user-images.githubusercontent.com/535300/41053259-e0b7f234-696f-11e8-844c-254748b01674.png)
![icon 3x](https://user-images.githubusercontent.com/535300/41053260-e0cfb45a-696f-11e8-9778-d726dcc8687d.png)

**Comment by velkymx** [comment]
Icon only

![pm-white-logo](https://user-images.githubusercontent.com/535300/41115797-6c7c47d4-6a3d-11e8-9a6a-bfb3ab0dcf06.png)

**Comment by velkymx** [comment]
This is completed
