### ISSUE TITLE
Installer: Create Database

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#232]
The current artisan installer is missing code to create the database. 

/ProcessMaker/Console/Commands/Install.php

Around line 115

**Comment by tdondich** [comment]
The database should already be created with appropriate permissions set by the admin.  So there's two tasks here, first, pmdev box should automatically created the workflow database during dev machine setup (as well as test database), and the installer should be updated with additional messaging to state the database should already exist.
