### ISSUE TITLE
API Loading

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#238]
When we load data from an API we'd like display a message letting the end user know that something is happening. This is typically done with a message and a spinning GIF.

**Comment by meadrat** [comment]
@velkymx this is ready for dev - https://zpl.io/29Z4nzz
<img width="913" alt="screen shot 2018-06-11 at 12 49 59 pm" src="https://user-images.githubusercontent.com/39599643/41253709-0b173346-6d76-11e8-8772-7d2307ac2609.png">
