### ISSUE TITLE
BPMN to JSON Object API

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#262]
We need away to convert the BPMN XML file to a JSON object that preservers all of the formatting and process information for use in rendering the process in the designer.

**Comment by velkymx** [comment]
After speaking with Taylor, there isn't a requirement to import XML in the Beta spec. I'm going to move this to cold storage until we are ready.

**Comment by marcoAntonioNina** [comment]
the parse of the xml will be done in the designer.
