### ISSUE TITLE
Add auth middleware check to appropriate tasks routes

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#268]
I should not be able to visit tasks page when unauthenticated.  It should redirect me to login.

**Comment by velkymx** [comment]
@marcoAntonioNina please update the task routes

**Comment by marcoAntonioNina** [comment]
The api routes for tasks are inside the middleware 'auth: api' and 'bindings',
for the int web route, apitoken

this redirects to login

**Comment by velkymx** [comment]
Thanks! I'll add this to the #143
