### ISSUE TITLE
User Profile Dropdown UI

### ISSUE THREAD

**Issue by meadrat** [ProcessMaker/bpm#278]
Link: https://zpl.io/2y7rB8w

<img width="259" alt="screen shot 2018-06-13 at 9 56 41 am" src="https://user-images.githubusercontent.com/39599643/41366173-1ebd60de-6ef0-11e8-8983-640873567ddf.png">

Use the menu builder to generate

**Comment by meadrat** [comment]
@velkymx this is ready for dev

**Comment by milaendo** [comment]
@meadrat @velkymx send feedback has been taken out per Taylor

**Comment by milaendo** [comment]
https://github.com/ProcessMaker/bpm/pull/309

**Comment by velkymx** [comment]
@milaendo The z-index issue persists. See below screen.

![screenshot 2018-06-27 09 19 54](https://user-images.githubusercontent.com/535300/41986550-52e813ee-79eb-11e8-8ad3-2cf40207ddb2.png)

**Comment by velkymx** [comment]
This was fixed in #345
