### ISSUE TITLE
Custom 404

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#289]
Create an error blade and set it to display when a route is not found or a 404 is thrown.

![image](https://user-images.githubusercontent.com/535300/41365764-2116f6f2-6eef-11e8-9b98-1714787f7f6d.png)

Design: https://zpl.io/V1qJDpJ

**Comment by velkymx** [comment]
@meadrat can you provide the PNG of the little guy?

**Comment by meadrat** [comment]
@velkymx I will ask Jayanta

**Comment by velkymx** [comment]
Here's the PNG of the robot

![robot](https://user-images.githubusercontent.com/535300/41478499-bc5e8bdc-707c-11e8-811d-37a7b2bb468b.png)
