### ISSUE TITLE
Admin, Customize Template

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#290]
A blade template is required to customize the interface of the template. In addition, a route will need to be configured for /admin/customize. Further ticket will deal with setting up the functionality.

Features include: Browser + Select Logos (with preview) and color pickers

![screenshot 2018-06-13 10 24 54](https://user-images.githubusercontent.com/535300/41367488-10786aa6-6ef4-11e8-8a62-9be36655e448.png)

Design: https://app.zeplin.io/project/5a872c6ffc8c7ad639253eb9/screen/5b0e69bc8b4ddae686cfbf11

**Comment by milaendo** [comment]
are the sizes of the logos correct? I am messing with the display now and 400X100 is a bit large. also the ticket says "Further ticket will deal with setting up the functionality", would you like me to do it in this ticket?
