### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#291]
The current forgot password screen needs to be restyled to match.

![screenshot 2018-06-13 10 44 36](https://user-images.githubusercontent.com/535300/41368445-d0adcefe-6ef6-11e8-9aa9-205d9899d11c.png)

Design: https://app.zeplin.io/project/5a872c6ffc8c7ad639253eb9/screen/5b0e6a6836d506c062d39491

**Comment by milaendo** [comment]
![screen shot 2018-06-14 at 10 38 07 am](https://user-images.githubusercontent.com/29641725/41428552-422f1164-6fbf-11e8-96f0-74317217ee4f.png)

**Comment by milaendo** [comment]
this ticket has a temporary path at /test. Taylor has suggested that there be a second ticket for creating the controller and route that would actually be used for this page.

**Comment by velkymx** [comment]
This is dependent on #300

**Comment by velkymx** [comment]
This is merged
