### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#307]
The user profile API need to be able to load the user's profile settings as well as save them back to the database. This is the GET and PUT functionality. Database changes may be required as well as the ability to save an image for the user's avatar. 

The api should live at the following API end point.

api/1.0/admin/profile

Works with the /admin/profile design #292

**Comment by marcoAntonioNina** [comment]
Solved with pull request https://github.com/ProcessMaker/bpm/pull/315

**Comment by velkymx** [comment]
@marcoAntonioNina please refactor the controller location to /Users/ProfileController.

**Comment by marcoAntonioNina** [comment]
Change location with pull request https://github.com/ProcessMaker/bpm/pull/336
