### ISSUE TITLE
Request Modal Issues

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#326]
The request modal is having z-index issue. 

![screen shot 2018-06-21 at 12 14 04 pm](https://user-images.githubusercontent.com/535300/41740405-c2d820ac-754c-11e8-8a91-68c58ce6646b.png)

**Comment by milaendo** [comment]
![screen shot 2018-06-22 at 3 13 29 pm](https://user-images.githubusercontent.com/29641725/41801334-d9a2c20a-762e-11e8-8459-d9c63ba5927f.png)


This was solved in #278

**Comment by velkymx** [comment]
This is resolved
