### ISSUE TITLE
Investigate Vue-Bootstrap Forms

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#378]
Review the underlying Vue form controls. In this ticket add your comments and thoughts as to how we can best leverage this to enhance our own vue form controls.

https://bootstrap-vue.js.org/docs/components/form/

**Comment by velkymx** [comment]
No sure why this is closed. Please review and update.

**Comment by milaendo** [comment]
- select has an option slot for the display, this is a very straight forward way to handle the visible option.
