### ISSUE TITLE
API timeouts

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#391]
Investigate why the API it "timing out" and not allowing further request.

**Comment by velkymx** [comment]
Related #362

**Comment by velkymx** [comment]
@caleeli can you review and confirm that the session timeout and the API token have the same expiration. Also confirm that subsequent page loads refreshes the time out for both.

**Comment by velkymx** [comment]
To reproduce, when logged in, run npm run dev. Then try to do anything.

**Comment by velkymx** [comment]
ALSO. Let the browser sit for 30 minutes and the token expires and the API file with {"error":"Unauthenticated."}

**Comment by velkymx** [comment]
You can't sign in after it fails. It shows: Client authentication failed

**Comment by velkymx** [comment]
The current work around is you need to clear all cookies, do a migration fresh and then sign back in.

**Comment by caleeli** [comment]
Okey, I got it, anyway actually the session timeout is set to 120minutes by default, and the API access and refresh tokens has 1 month and 1 year of expiration

**Comment by caleeli** [comment]
at ProcessMaker/Providers/OAuthServiceProvider.php::73
`
            // Allow the CLient Credentials Grant Type
            $grant = new ClientCredentialsGrant();
            $grant->setRefreshTokenTTL(new DateInterval('P1M'));
            $server->enableGrantType(
                $grant,
                new DateInterval('P1Y')
            );
`
