### ISSUE TITLE
Remove Unused Designer Options

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#404]
In process objects menu, update the items to only include these ones. Also remove and corresponding code for removed items. 
![screenshot 2018-07-20 13 07 38](https://user-images.githubusercontent.com/535300/43022974-0d67ec0a-8c1e-11e8-877e-73b17f6b6789.png)

**Comment by marcoAntonioNina** [comment]
solved with https://github.com/ProcessMaker/bpm/pull/420

**Comment by marcoAntonioNina** [comment]
solved with pull https://github.com/ProcessMaker/bpm/pull/420
