### ISSUE TITLE
New Process

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#405]
When you click on the + Process, show this modal and set up and initial BPMN file. Redirect to the designer. Use the create process API.

![screenshot 2018-07-20 13 11 51](https://user-images.githubusercontent.com/535300/43023114-89af942a-8c1e-11e8-8085-bc502e14b8af.png)

**Comment by marcoAntonioNina** [comment]
solved with https://github.com/ProcessMaker/bpm/pull/419
