### ISSUE TITLE
openssl_csr_sign(): cannot get CSR from parameter

### ISSUE THREAD

**Issue by MortezaFathi** [ProcessMaker/bpm#442]
Hi,
During the installation we getting this error: openssl_csr_sign(): cannot get CSR from parameter

![capture](https://user-images.githubusercontent.com/5616925/43566766-ccf595a6-9644-11e8-93d7-56f0c50615bd.JPG)

Please attache the installation manual.

**Comment by velkymx** [comment]
Do you have OpenSSL installed?

**Comment by MortezaFathi** [comment]
Yes, OpenSSL is installed on my system @velkymx

**Comment by MortezaFathi** [comment]
Tnx,
I solved my problem and BPM was successfully installed, but I have another problem with its running.
Please, if possible, give me complete instructions on installing and running.
