### ISSUE TITLE
Variables List

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#449]
Remove the Variables from the project entirely. This includes removing the menu from the vue components, the menus and anywhere else they are called.

<img width="259" alt="screenshot 2018-08-17 13 16 19" src="https://user-images.githubusercontent.com/535300/44286951-cbb32000-a21f-11e8-9c99-1384cb7a452a.png">

**Comment by marcoAntonioNina** [comment]
the table report_table_columns use the field process_variable_id, It is necessary the definition of how you should work now.

**Comment by velkymx** [comment]
Wait to work on this
