### ISSUE TITLE
List Forms

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#451]
When I click on the Process Objects menu "forms" button, I want to see a list of forms configured for the process and be able to edit and delete them. 

![screenshot 2018-08-06 11 00 43](https://user-images.githubusercontent.com/535300/43733223-cc875fe2-9968-11e8-855a-d4bb9f1430cb.png)

**Comment by marcoAntonioNina** [comment]
@velkymx this ticket is resolved in the branch developed with merge branch nayraForm
