### ISSUE TITLE
Laravel Media Library

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#464]
We need to replace the Avatar upload and all future uploads (docs, pdfs, etc, etc) to use the Laravel Media Library. It takes care of uploads, storage and links. Check out the link below for details. For this first issue, update all of the user avatar code to use this. 

https://docs.spatie.be/laravel-medialibrary/v7/introduction

**Comment by marcoAntonioNina** [comment]
resolved with pull request https://github.com/ProcessMaker/bpm/pull/490
