### ISSUE TITLE
Grid Component Styling

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#467]
The grid component we're using needs to be updated with the following changes.

- Selected headers should be #333333
- Action buttons are the wrong color #788793
- Status bubbles CSS doesn't match. Use Bootstrap classes
- Change all dates columns to be just the word (created instead of created_on change to created, etc)
- Search box doesn't match mockup

<img width="1163" alt="screenshot 2018-08-07 11 58 24" src="https://user-images.githubusercontent.com/535300/43796457-337fbeb2-9a39-11e8-9f28-a6271559693c.png">

**Comment by velkymx** [comment]
For the circles use the bootstrap pills. 

https://bootstrap-vue.js.org/docs/components/badge#pill-badges

<b-badge pill variant="primary">Primary</b-badge>

**Comment by KillahDillah** [comment]
Search Bar has been updated to match mockup
header color change to match mock up
status bubbles change color according to status type, however not sure this is the preferred method

**Comment by velkymx** [comment]
Regular column (non-selected) the text should be #788793

**Comment by velkymx** [comment]
Please go through all screens and make sure the bubble is updated to the smaller size.
