### ISSUE TITLE
Modal Footer Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#468]
All buttons need to updated to use "success" CSS class for both buttons. This effects all modals. 

<img width="481" alt="screenshot 2018-08-07 12 06 12" src="https://user-images.githubusercontent.com/535300/43796856-4a1fd12e-9a3a-11e8-8476-3938cb2fa7c9.png">

**Comment by velkymx** [comment]
Solid button is btn btn-primary btn-sm text-uppercase

Outline is btn btn-outline-success btn-sm text-uppercase

**Comment by KillahDillah** [comment]
<img width="644" alt="screen shot 2018-08-08 at 1 36 31 pm" src="https://user-images.githubusercontent.com/29666170/43862991-3610066e-9b10-11e8-99c4-b152dab8b7d7.png">

Searched for b-modal and buttons with primary bootstrap class. Manually changed each one individually.

Modal's that need SLOT : 
modal-forms-list,
modal-input-document-list,
modal-output-document,
modal-triggers-list,
modal-profile-avatar

https://github.com/ProcessMaker/bpm/pull/479
