### ISSUE TITLE
Create Notifications Configuration Area

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#470]
We need a new route /admin/notifications for managing the SMTP setting of the app. 

Should be a form that saves back to an API and include tests. 

Use this screen for fields. Additional styling will be required.

![screenshot 2018-08-07 12 25 52](https://user-images.githubusercontent.com/535300/43797708-18f097f2-9a3d-11e8-9d3a-4c767e6f9f00.png)

**Comment by milaendo** [comment]
![screen shot 2018-08-10 at 1 39 51 pm](https://user-images.githubusercontent.com/29641725/43980462-0c62461c-9ca3-11e8-8f0c-60e6595b7957.png)

**Comment by velkymx** [comment]
It's supposed to be a form. Not a page with fields.

**Comment by velkymx** [comment]
Use that layout, but our form controls.

**Comment by velkymx** [comment]
![screenshot 2018-08-10 15 34 23](https://user-images.githubusercontent.com/535300/43984055-f134aece-9cb2-11e8-9173-8fcc719c2e85.png)
