### ISSUE TITLE
Requests List Changes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#531]
Here is a simplified layout. 

For the ID column,  use primary auto-increment ID and make it click to open the request detail screen.

For the assigned column, we should show the assigned user's avatar. If there are multiple users assigned/participating show their avatar, if there are more than 5 show a badge with the number of part. Include tooltips with the user's name.

For the due date column, if any of the tasks are unfinished and exceeded their due date, we show that the request is overdue. Use Overdue, At Risk and On Time

![screenshot 2018-08-17 09 52 21](https://user-images.githubusercontent.com/535300/44279275-a31e2c80-a205-11e8-8577-8cc77138c893.png)

**Comment by marcoAntonioNina** [comment]
-a case (request) can be in different tasks at the same time. Every task will have its own due date. In the mock-up is not clear how these multiple dates should be dispalyed
-In the first column, right to id, there is an icon. what is the use of this icon? what icon we must to use?

**Comment by velkymx** [comment]
No. Multiple tasks should only result in a unique list of assigned users. 

Per the issue: if any of the tasks are unfinished and exceeded their due date, we show that the request is overdue. Use Overdue, At Risk and On Time instead of a date.
