### ISSUE TITLE
Site Preferences Screen

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#536]
Setup a route for /admin/preferences/ 
Hook up the admin sidebar menu
Show this page

![screenshot 2018-08-17 10 34 19](https://user-images.githubusercontent.com/535300/44280302-3311a580-a209-11e8-9cad-e7fcb7efe2b2.png)

**Comment by milaendo** [comment]
#470 will be combined with this page

**Comment by milaendo** [comment]
![screen shot 2018-08-21 at 3 06 33 pm](https://user-images.githubusercontent.com/29641725/44431887-ab9f9b80-a554-11e8-92ac-bf1b6d39438f.png)

**Comment by milaendo** [comment]
![screen shot 2018-08-22 at 10 13 49 am](https://user-images.githubusercontent.com/29641725/44479005-2966b400-a5f4-11e8-9e8f-fc3beffea010.png)
