### ISSUE TITLE
Edit User Group

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#539]
In the Groups area /manage/groups 

When you click on the edit action button show a modal that allows you to edit the name of the group and change the status. On save post to API. Include validation on the front end and Unit Test to confirm the edit API end points are working.

**Comment by caleeli** [comment]
@velkymx The 'CODE' was UNIQUE. Do the 'NAME' should be UNIQUE?

**Comment by caleeli** [comment]
The constants to make reference to the roles where related to the CODE, like PROCESSMAKER_ADMIN where strings, now do the references should be the ID or NAME?
If ID, the IDs of the initial roles should be constants (ex. PROCESSMAKE_ADMIN=1, ...)
If NAME, the names should be constants :/
