### ISSUE TITLE
Remove Role CODE

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#541]
Remove "Code" entirely. Include migrations, tests, forms and grid. Use the role name instead. Always use the ID to reference which role.

**Comment by caleeli** [comment]
@velkymx does the ID of the Roles Administrator, Manager, Operator, Guest will be constants?

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/44354415-cb14c680-a477-11e8-8eb3-0072d344b2a1.png)

![image](https://user-images.githubusercontent.com/8028650/44354432-d2d46b00-a477-11e8-8d35-c4cf50e40f20.png)

![image](https://user-images.githubusercontent.com/8028650/44354444-dbc53c80-a477-11e8-9142-876367db0dd2.png)

**Comment by velkymx** [comment]
Roles to be removed
