### ISSUE TITLE
Tasks Grid Update

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#545]
Update the data grid to match. Make Task Title clickable to the task.

Grid cols: Title, Process, Assigned to, Created by, Due

![screenshot 2018-08-17 10 58 50](https://user-images.githubusercontent.com/535300/44281775-baf9ae80-a20d-11e8-85d1-fc013aecef36.jpg)

**Comment by caleeli** [comment]
@velkymx What does the pause and the undo buttons?
![image](https://user-images.githubusercontent.com/8028650/44343699-ac550680-a45c-11e8-9c40-6ff425902b22.png)
