### ISSUE TITLE
Update Validation

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#567]
Update all of the validation to use the pattern established in the UsersController and Users model.

Move rules to the Model like:

`public static function rules(User $existing = null) {
        $rules = [
        'firstname' => 'nullable',
        'lastname' => 'nullable',
        'password' => 'required',
        'status' => 'required|in:ACTIVE,DISABLED',
        ];
        if($existing) {
            $rules['username'] = [
                'required',
                Rule::unique('users')->ignore($existing->id)
            ];
        } else {
            $rules['username'] = 'required|unique:users';
        }
        return $rules;
    }`

Then call it via the Controller like this:

`$request->validate(User::rules($user));`

**Comment by nolanpro** [comment]
@velkymx curious what your thoughts are on allowing the model to handle all validations (it's how they do it in the rails world 😃): Here's an example for users: https://github.com/ProcessMaker/bpm/commit/a03811f58aa5604c30b6b43e9899f5a856858168

**Comment by nolanpro** [comment]
@velkymx Yeah that makes sense

**Comment by nolanpro** [comment]
Implemented
