### ISSUE TITLE
Blade Organizations

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#650]
Follow this pattern.

For example: to view uses;

/admin/users/index.blade.php

to edit

/admin/users/edit.blade.php

GET | /photos | index | photos.index
GET | /photos/create | create | photos.create
GET | /photos/{photo} | show | photos.show
GET | /photos/{photo}/edit | edit | photos.edit

Default template:

@extends('layouts.layout', ['title' => __('Processes Management')])

@section('sidebar')
  @include('layouts.sidebar', ['sidebar'=> Menu::get('sidebar_admin')])
@endsection

@section('content')
@endsection

@section('js')
@endsection

**Comment by velkymx** [comment]
@milaendo let's get a master list of routes in this ticket so we can check them off. Would you prefer individual tickets?

**Comment by velkymx** [comment]
@meadrat can you help with that too?

**Comment by milaendo** [comment]
I dont mind keeping it in this one ticket but I agree we should have a list to make it easier :)
