### ISSUE TITLE
List Groups

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#658]
Show a list of groups, click to edit groups.

Path: /admin/groups

HTML: https://github.com/ProcessMaker/ui/blob/master/Admin/groups.html

Include UI tests for Route and Page Content

**Comment by KillahDillah** [comment]
#671

**Comment by KillahDillah** [comment]
Included content for Admin/groups/Index and Edit
Added routes to web.php
Views inside GroupController
All tests pass within GroupTest

GroupController does not include ' compact($group) ' as tests fail upon use - array usage instead

**Comment by KillahDillah** [comment]
Group Controller now has compact
