### ISSUE TITLE
App Preferences

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#661]
Add the page for app preferences. 

Path: /admin/preferences

HTML: https://github.com/ProcessMaker/ui/blob/master/Admin/preferences.html

Include UI tests for Route and Page Content

**Comment by velkymx** [comment]
@milaendo Please bring in the values from the json arrays we have in the vue stuff.

**Comment by velkymx** [comment]
Also place holder text needs to be updated to match the fields they are for.

**Comment by milaendo** [comment]
![screen shot 2018-10-08 at 1 56 16 pm](https://user-images.githubusercontent.com/29641725/46633256-0475c400-cb02-11e8-8196-761305ce1035.png)
