### ISSUE TITLE
Docker CI Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#692]
Response Debug Information:
/home/circleci/repo/tests/Feature/Shared/RequestHelper.php:51:
array(1) {
  'output' =>
  string(149) "/usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker run --help'."
}

**Comment by tdondich** [comment]
What does this mean? Where is this error occuring? What's the meaning of life?

Please provide link to circleci if it's a broken build. What branch is this?

**Comment by velkymx** [comment]
@tdondich the CircleCI automated testing is complaining about it. This is one of the last holdouts to get CI all passing.

**Comment by velkymx** [comment]
Seems to be working now. Will reopen if the issue comes back. Thank you @daniel-ryan-PM
