### ISSUE TITLE
Implement permissions for groups and users

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/bpm#697]
List of permissions:
https://processmaker.atlassian.net/wiki/spaces/PM4/pages/401801296/Permissions+List

Laravel Gates:
https://laravel.com/docs/5.7/authorization#gates

**Comment by velkymx** [comment]
Move the permissions into the Auth session.

**Comment by velkymx** [comment]
@nolanpro also make sure to respect the is_administrator flag in the user table to give unrestricted access to the site.

**Comment by nolanpro** [comment]
@velkymx should be good to go, reopened the PR
