### ISSUE TITLE
Create the UI and backend end points for the requests lists

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#7]
Description
Tha main lists used by ProcessMaker must be created. Those listings must follow the logic and must use the tables of the current version of ProcessMaker.

The specification of how the current endpoints work can be found in:

https://processmaker.atlassian.net/wiki/spaces/PM/pages/241238066/Cases+List+ProcessMaker+4.0

**Comment by velkymx** [comment]
This is completed
