### ISSUE TITLE
Add Script Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#705]
Enable the add script button in the /processes/scripts/ page. Show the new script modal, save and go to the /processes/scripts/{id} page.

**Comment by milaendo** [comment]
<img width="585" alt="screen shot 2018-10-09 at 4 06 40 pm" src="https://user-images.githubusercontent.com/29641725/46703840-52132f00-cbdd-11e8-84e7-79bf304700be.png">
modal is in and toggle is workin correctly, waiting for final design for the modal from @meadrat

**Comment by milaendo** [comment]
testListScriptsWithQueryParameter has been marked as skipped, can we figure out if description is needed? there are some inconsistencies from the api and the front end mockups
