### ISSUE TITLE
DEPRECATION WARNING in Sass

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#709]
/sass/app.scss 

DEPRECATION WARNING on line 11, column 8 of stdin:

Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.

Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

**Comment by milaendo** [comment]
@velkymx since updating to npm version 6.4.1 the errors have disappeared. I think its safe to close the ticket
