### ISSUE TITLE
Processes Menu

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#713]
The processes menu needs to be implemented. Items include...

1. Processes
2. Process Categories
3. Scripts
4. Forms
5. Environmental Variables

<img width="128" alt="screenshot 2018-10-05 12 41 33" src="https://user-images.githubusercontent.com/535300/46556616-00486d00-c89c-11e8-86d5-860b6c552d06.png">

**Comment by milaendo** [comment]
@meadrat  are these all font awesome icons?
