### ISSUE TITLE
Refactor Script Preview Method

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#717]
The current state of the method: Api\ScriptController\preview needs to be refactored to be in a more testable state. Corresponding unit test needs to be updated as well.

**Comment by caleeli** [comment]
This test requires docker and the scripts execution environment to run. Added a validation before to execute or skip the test.
PR #720

**Comment by velkymx** [comment]
@caleeli  Failing tests both in CI and locally.

Response Debug Information:
/home/circleci/repo/tests/Feature/Shared/RequestHelper.php:51:
array(1) {
  'output' =>
  string(149) "/usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker run --help'."
}

............. 126 / 161 ( 78%)
...................................                             161 / 161 (100%)

Time: 2.34 minutes, Memory: 68.25MB

There was 1 error:

1) Tests\Feature\Api\ScriptsTest::testPreviewScript
PHPUnit\Framework\Exception: Argument #2 (No Value) of PHPUnit\Framework\Assert::assertArrayHasKey() must be a array or ArrayAccess

/home/circleci/repo/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:599
/home/circleci/repo/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:597
/home/circleci/repo/tests/Feature/Api/ScriptsTest.php:242
