### ISSUE TITLE
CI Deployments Failing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#718]
#!/bin/bash -eo pipefail
# Delete existing target QA directory, if it exists
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "rm -Rf ~/builds/$BUILD_NAME"
# Create new target QA directory
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "mkdir ~/builds/$BUILD_NAME"
# Copy over packaged qa deployment
scp -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" ./processmaker-qa-$BUILD_NAME.tar.gz qa-pm4builds:~/builds/$BUILD_NAME/
# Extract to qa deployment dir
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "tar zxf ~/builds/$BUILD_NAME/processmaker-qa-$BUILD_NAME.tar.gz -C ~/builds/$BUILD_NAME/"
# Restart nginx and php-fpm to clear cache
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "sudo service nginx restart"
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "sudo service php-fpm restart"
# Create MYSQL Database
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "mysql -h ${QA_RDS_HOST} -u ${QA_RDS_USERNAME} -p${QA_RDS_PASSWORD} -e \"CREATE DATABASE IF NOT EXISTS ${QA_DB_NAME}\""
# Run php artisan migrate:fresh --seed to have a clean installed database in RDS
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "php ~/builds/$BUILD_NAME/artisan migrate:fresh --seed --force"
# Setup Media Link
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "rm -Rf ~/builds/$BUILD_NAME/public/storage"
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "php ~/builds/$BUILD_NAME/artisan storage:link"
echo "Deployed to https://${BUILD_NAME}.bpm4.qa.processmaker.net/"
# Run containerDeploy.sh script to spin up Redis docker container, laravel-echo-server, and horizon
ssh -o "ProxyCommand ssh buildbot.processmaker.net -A -W %h:%p" qa-pm4builds "sudo /bin/bash /root/cloudops/containerDeploy.sh $BUILD_NAME"
Warning: Permanently added the ED25519 host key for IP address '34.194.215.175' to the list of known hosts.

mkdir: cannot create directory '/home/circleci/builds/feature-657': Permission denied
Exited with code 1

**Comment by daniel-ryan-PM** [comment]
permissions not set on builds dir after morning volume maintenance.
corrected by giving circleci ownership to it's build dir.

**Comment by velkymx** [comment]
Works!
