### ISSUE TITLE
Nayra Composer Problem

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#721]
When running composer update, the Nayra package reverts back to 9999999-dev. This overwrites the composer.lock with bad settings and causes the tests to fail.

**Comment by velkymx** [comment]
Problem stems from the /home/vagrant/.composer/config.json file. The configuration is symlinking incorrectly and causing an issue with the composer update.

**Comment by velkymx** [comment]
`{
    "repositories": {
        "0": {
            "type": "path",
            "url": "/opt/bpm-plugins/*",
            "options": {
                "symlink": true
            }
        }
    }
}`

**Comment by velkymx** [comment]
@tdondich can you check the vagrant config?

**Comment by caleeli** [comment]
Solved at vagrant/composer configuration for bpm4 stack:

https://bitbucket.org/colosa/pmdev/pull-requests/4/remove-symlink-configuration-for-nayra-it
