### ISSUE TITLE
Hook Up Edit Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#724]
On the VueTables integrated into the UI. Connect the edit icon to the corresponding edit page. Please update this ticket with any lists you find that are incomplete.

**Comment by milaendo** [comment]
tables not in: 
-requests list
-tasks
-processes seems like it might be an old table? (modals still function)
-groups 
-queue monitors

**Comment by milaendo** [comment]
Tables with Edit buttons wired up:
- scripts
