### ISSUE TITLE
Add OAuth login to swagger UI

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/bpm#727]
Should use a 3-legged OAuth flow so we don't have to generate a personal access token every time we want to try it out.

**Comment by velkymx** [comment]
This isn't working correctly. The OAuth 2.0 3 legged auth should work with the api documentation in order to authorize the api docs. I shouldn't have to include a bearer token.

**Comment by tdondich** [comment]
See: http://oauthbible.com/#oauth-10a-three-legged
