### ISSUE TITLE
Tasks List

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#747]
Enable the Vuetables to show tasks at /tasks/

<img width="1158" alt="screenshot 2018-10-12 09 07 18" src="https://user-images.githubusercontent.com/535300/46880700-3cc91b00-cdfe-11e8-8a59-5caf5d2b5c71.png">

**Comment by danloa** [comment]
@meadrat, @velkymx  
 I have some questions about the user's avatar:

1. If there isn't any previous user (fox example this will happen in the first task of a process), what will be shown in the column SENT BY? (will it be blank? or maybe a text like "None" should be displayed?)
2. If the user hasn't an avatar, what will be shown? (an empty avatar, the user's name initials?)
