### ISSUE TITLE
Clean Horizon Structure

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#752]
Horizon has lots of artifacts in the code. We need to review and remove anything we don't need.

**Comment by milaendo** [comment]
![screen shot 2018-10-17 at 2 11 52 pm](https://user-images.githubusercontent.com/29641725/47116489-a68a6000-d216-11e8-8e06-ba2a8afe5942.png)
fixed route and got the page to show up again under admin/queues

**Comment by milaendo** [comment]
@nolanpro @velkymx I may need someone else to step in and take this over, Im not exactly sure what this does but I did get it back into the code base.

**Comment by PaolaPellegrini** [comment]
1. Import the process [FOUR 1525 File Upload Test.json.txt](https://github.com/ProcessMaker/processmaker/files/4754631/FOUR.1525.File.Upload.Test.json.txt)
2. Start a new request
3. Upload a file
4. Add other files
5. Download

It does not show all the files that have been loaded in the previous screen. Only the first file is displayed.
see  the  video ----* https://drive.google.com/file/d/1kBcrAE0Ydj7Xv2_S5N19DFOjpNlpZNcI/view?usp=sharing 

The  solutions  is  rejected
