### ISSUE TITLE
CSS Not Using Bootstrap Classes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#772]
The current CSS for VueTables and a few other elements is not using standard bootstrap classes and styling. We need to remove this custom CSS and use the bootstrap ones for theming.

EX: After this code in layout.blade

``<link href="{{ mix('css/sidebar.css') }}" rel="stylesheet">``

Add

``<link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css">``

**Comment by velkymx** [comment]
<img width="352" alt="screenshot 2018-10-17 13 32 10" src="https://user-images.githubusercontent.com/535300/47114602-244b6d00-d211-11e8-84e7-0a2aec0311f0.png">

**Comment by velkymx** [comment]
The sidebar is also wonky with a different theme.

![screenshot 2018-10-08 14 16 43](https://user-images.githubusercontent.com/535300/47168852-d7ba6d00-d2b6-11e8-9cc4-14268f4aa6fc.png)

**Comment by velkymx** [comment]
<img width="234" alt="screenshot 2018-10-18 09 18 36" src="https://user-images.githubusercontent.com/535300/47168885-ebfe6a00-d2b6-11e8-8fc2-7be9d2583e4d.png">

**Comment by UnderDogg** [comment]
Maybe not same issue, but similar issue. When you open the user menu and then the tasks menu (or vice versa, they overlap each other and opening one doesn't close the other menu
