### ISSUE TITLE
Fix Table Titles

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#782]
<img width="324" alt="screenshot 2018-10-19 09 32 51" src="https://user-images.githubusercontent.com/535300/47231525-f89bc480-d381-11e8-9446-9d108494fd0a.png">

Move the title up. It's not aligned.

**Comment by milaendo** [comment]
![screen shot 2018-10-19 at 9 36 36 am](https://user-images.githubusercontent.com/29641725/47231728-9abbac80-d382-11e8-9daf-70e77a35a1b1.png)

**Comment by velkymx** [comment]
@milaendo I'm going to take this. We settled on an updated layout.

**Comment by velkymx** [comment]
@milaendo take over using the Users list as the pattern.
