### ISSUE TITLE
Create User Modal

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#788]
Make it work with validation. Redirect to the /admin/user/edit page

![screenshot 2018-10-19 14 14 58](https://user-images.githubusercontent.com/535300/47244187-6e675680-d3a9-11e8-9ea7-fde38da1e625.png)

**Comment by velkymx** [comment]
@marcoAntonioNina we need you to integrate the multiselect Vue control. This will need to pull in the active groups from the API to populate the control.

**Comment by tdondich** [comment]
merged into develop
