### ISSUE TITLE
Passport Client Access

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#816]
During the install process, create an oauth client that can be used for API Documentation.  Then ensure the configuration for the api documentation uses the oauth client created.  This should help facilitate the 3 legged oauth and not prompt the user to have to put in the oauth client details when they authenticate the api docs.

![image](https://user-images.githubusercontent.com/535300/51133376-b3085f80-17e9-11e9-9567-4e6c72622458.png)

![image](https://user-images.githubusercontent.com/535300/51133389-bb609a80-17e9-11e9-80cf-cfa3c85e4244.png)

**Reference**

https://mattstauffer.com/blog/introducing-laravel-passport/
https://laravel.com/docs/5.7/passport#managing-clients

- [x] List client tokens
- [ ] Unit test token works/fails and can be created / regenerated

**Comment by ryancooley** [comment]
@velkymx I believe this has already been closed by #823. I am able to access API docs and test them using existing oauth credentials.

**Comment by velkymx** [comment]
This is related to the API Client info not the personal user tokens.

**Comment by velkymx** [comment]
@nolanpro I'll note that for a future ticket. For now, this is outside of the scope of the ticket.
