### ISSUE TITLE
Request Detail Page

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#829]
Title is the name of the Process + ID

The tabs are:

In Progress - tasks for that request that are open
Request Summary - that is blank place holder if there are in progress tasks, if the request is completed it will show key value pairs
Complete - list of tasks that are completed for that request

REMOVE CANCEL REQUEST

<img width="1140" alt="screenshot 2018-10-26 11 50 20" src="https://user-images.githubusercontent.com/535300/47586719-d4a62900-d915-11e8-8ae6-f4c75c8a21b0.png">

<img width="368" alt="screenshot 2018-10-26 11 51 26" src="https://user-images.githubusercontent.com/535300/47586717-d4a62900-d915-11e8-8f09-1279c5688650.png">

<img width="372" alt="screenshot 2018-10-26 11 51 58" src="https://user-images.githubusercontent.com/535300/47586718-d4a62900-d915-11e8-83f3-5389b086ac20.png">

HTML TEMPLATE HERE: https://www.dropbox.com/s/rgekpcb3o8xpnsq/blade_template.txt?dl=0

**Comment by velkymx** [comment]
> Define expected behavior, functionality, and UX around cancelling a request.

We need a PRD for how that will work (notifications, what screens change, etc)

**Comment by mattmclaren** [comment]
Standardize the way we display times in different scenarios.

**Comment by caleeli** [comment]
Define a design to show the key values in the Summary Tab

**Comment by velkymx** [comment]
> Standardize the way we display times in different scenarios.

For now time is always in military time MM/DD/YYYY HH:MM

**Comment by danloa** [comment]
We need to add the list of participants of a request in the model

**Comment by velkymx** [comment]
PRD We need a definition on how the time is displayed for the users when their timezone is different than the system default. We should also probably talk about custom date formatting.

**Comment by mattmclaren** [comment]
Define functionality around Watchers.

**Comment by velkymx** [comment]
NO SCRIPT TASKS in the task

**Comment by velkymx** [comment]
If due date on a task on the list is expired. Make text red.

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/47589008-f3b4b300-d935-11e8-8d8e-8322f783e139.png)
fa calendar-times

**Comment by tdondich** [comment]
If there are script tasks that are pending, or in progress, or the process/request has halted due to a script task breaking or taking a long time, do we need to reflect this initially?  I'm okay with a clear answer of no.  Ideally script tasks are handled quickly, and we don't care. 8)

**Comment by velkymx** [comment]
Task should update on the Pending Tasks like in real time (don't forget)

**Comment by caleeli** [comment]
@velkymx, There will be action buttons in the Pending Tasks list?

In the HTML template there are 3 buttons:
![image](https://user-images.githubusercontent.com/8028650/47726375-be0f1300-dc30-11e8-831f-fc8944faf601.png)

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/47731787-37136800-dc3b-11e8-8608-690b424a3c0d.png)
This card requires to register the date when a Request change to an ERROR status. Are we going to create "**failure_at**" field in the request table?
