### ISSUE TITLE
Tasks List Modifications

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#832]
By default all task grids have the following columns:

ID
Task Title (click to task detail)
Request Title (click to request summary)
Assignee (click to profile)
Due Date (if configured)

Action button: NONE

There are to be two different views into tasks. They are icons that show in the left sidebar menu.

1. To Do - this is a list of tasks assigned to me that have not been completed
2. Completed - this is a list of tasks assigned to me that have been completed

Acceptance Criteria

Test to show /tasks
Test to show /tasks/?status=closed

Two test to makes sure the API works for those pages.

**Comment by milaendo** [comment]
ID column has been added into the data table
