### ISSUE TITLE
Task Detail Page

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#833]
Open

![screen shot 2018-10-26 at 10 30 08 am](https://user-images.githubusercontent.com/535300/47582817-52fcce00-d90a-11e8-8212-357b01c755ae.png)

Completed

![screenshot 2018-10-26 10 35 44](https://user-images.githubusercontent.com/535300/47583010-f2ba5c00-d90a-11e8-8469-58ce433d4e2d.png)

Overdue

![screenshot 2018-10-26 10 31 00](https://user-images.githubusercontent.com/535300/47582823-555f2800-d90a-11e8-8dfa-d2e5ef3c9d4c.png)

Acceptance Criteria

Three test to load the task and see "Open, Completed, Overdue" in the UI

**Comment by velkymx** [comment]
We need to load a screen from the screen builder
We need to be able to submit the task to the API and complete it
We need three different sidebars (Open, Completed and Overdue)

**Comment by velkymx** [comment]
PRD for pausing and changing due dates on tasks

**Comment by velkymx** [comment]
If the task is a manual task, show the title as normal, but in the body show the description and a GREEN button that says, "Mark as Completed"

**Comment by tdondich** [comment]
@velkymx As I mentioned, we need/ideally, could be optional, user defined screen, to show for manual tasks.  Can we specify that?

**Comment by velkymx** [comment]
@tdondich I like that. Everything would be a form task at that point.

**Comment by velkymx** [comment]
@caleeli Avatar images need to click through to the profile/{id} page to view the profile of that person.

**Comment by velkymx** [comment]
Also the branch is in conflict with develop
