### ISSUE TITLE
View User Profile Page

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#834]
Route /profile/{id}

Details to come

**Comment by milaendo** [comment]
![screen shot 2018-10-29 at 1 25 23 pm](https://user-images.githubusercontent.com/29641725/47678086-1e914800-db7e-11e8-9d37-7e55c1145287.png)
@velkymx this still needs the avatar component in when that ticket is complete

**Comment by milaendo** [comment]
this ticket will also have failing tests until 797 is merged in. there will be conflicts with the two that will need to be resolved.

**Comment by milaendo** [comment]
![screen shot 2018-10-29 at 3 13 04 pm](https://user-images.githubusercontent.com/29641725/47683556-286e7780-db8d-11e8-9fcc-2ae258dcc838.png)
