### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#856]
Lean parent tables (id, timestamps)
Models: two methods - latests and versions
API: load the latest version merge with parent return flat array
PARENT: screens
VERSIONS: screen_versions (fk to screen_id)
CREATE will add a top parent record (screen)
CREATE or UPDATE will create version record (screen_versions) and then save the data to the child

NO CHANGES to the UI or AXIOS

Acceptance test:

Test to see if there is a version on create
Test to see if there is more children on update

ENGINEERING NOTES

When you add a hasMany versions function to the model, creating a new version in the controller should be as simple as
```
$model->versions->create($request->all());
```
We can do this in both the update and store functions

For returning the record, we can update the resource. If the controller is calling `ApiResource` directly, create a new resource that inherits it. For example, `class ProcessResource extends ApiResource` then merge the version and it's parent in there. Make sure the ID returned in the payload is the parent, not the version.

**Comment by nolanpro** [comment]
@velkymx After playing with this for a while I think having a separate version table for each model that needs to be versions can create some headaches (for example unique rules) and code changes in lots of places.

Taylor mentioned we should look at the [versionable](https://github.com/mpociot/versionable) plugin which is very similar paper_trail gem i've used in rails. It seems to support all the functionality we need like auditing and reverting. After looking it over I think it's a good option. Let me know what your thoughts are

**Comment by velkymx** [comment]
After discussion, the parent table should mirror the fields in the versions. Then when a save happens, the current parent version is saved into the versions table and then the parent table is updated. This will eliminate the need for the latest.
