### ISSUE TITLE
Date Time

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#858]
API return ISO::8601 formatted string ('2012-06-15T18:33:00+03:00' for example)
Remove timezone from UI in Preferences
Timezone in .env

User's timezone in UI (verify saving correctly)
Edit user screen UI
Profile edit UI
Default to Application time

Need to apply the user's timezone
Tasks list 
Requests list 
Request detail
Task detail

Engineering Note: I think this can be done in ApiResource without specifying each date/datetime field. Check the column type in the resource and if its date or datetime, foramt it is 8601
```
$attribute->toIso8601String()
```
For the API I think the API should always return the 8601 string without changing it for the user's timezone. Moment js can format it to the user's specified timezone

**Comment by danloa** [comment]
PR: https://github.com/ProcessMaker/bpm/pull/881
