### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#859]
Set default from a list of common formats in the installer save to .env
Date: Short (MM/DD/YYYY) Long MM/DD/YYYY h:i g or MM/DD/YYYY H:i
Remote the admin UI
Translate dates in the ui to the format
UI needs to convert (blade + javascript dates)
Vue-Tables to accept datetime + timezone
Maybe store in the meta?

Engineering note: For blade templates, I think the users timezone and date format should be set in `<meta>` tags in the HTML head in the layout. Moment JS should read those and use appropriately.

For the dropdown that the user selects (and maybe the defaults in the .env file too), the value might need to be a JSON string that has both formatting for php (carbon) and javascript (moment) like this:
```
<option value='{"php_date" : "MM/DD/Y", "js_date" : "MM/DD/YYYY", "php_short_datetime":"MM/DD/YYYY H:i" .... etc
```

**Comment by danloa** [comment]
PR: https://github.com/ProcessMaker/bpm/pull/881
