### ISSUE TITLE
Change App Logos

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#860]
Add two logos - have them resize to the correct widths and save to the database and have the layout blade use the new logo. 

The two logos are: the icon logo, the text logo

Places to update

menu closed (icon)
menu open (text)

login page (text)

**Comment by milaendo** [comment]
@velkymx I believe it will be three different logos because the login page is the blue text logo, do you agree or should we assume they will only be uploading two different images?

**Comment by milaendo** [comment]
![screen shot 2018-11-05 at 1 16 00 pm](https://user-images.githubusercontent.com/29641725/48027276-3aa46480-e0fd-11e8-9e2e-1d4e5614da93.png)

**Comment by milaendo** [comment]
TODO: update readme, add info for adding a custom logo.

**Comment by velkymx** [comment]
Please rename the default assets to:

processmaker_logo.png
processmaker_icon.png
processmaker_login.png

**Comment by velkymx** [comment]
@milaendo this page doesn't work. Also the avatar in the header is off for some reason.

<img width="1112" alt="screenshot 2018-11-15 08 12 50" src="https://user-images.githubusercontent.com/535300/48565833-54d50400-e8ae-11e8-9c3a-8480fe4e9257.png">

![screenshot 2018-11-15 08 12 41](https://user-images.githubusercontent.com/535300/48565834-54d50400-e8ae-11e8-99b2-ee78131b7b1e.png)

**Comment by milaendo** [comment]
@velkymx this is old code that needs to be removed. I will do that now
