### ISSUE TITLE
Create support for modeler to load custom javascript/extensions when rendering

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/bpm#877]
When the modeler is about to load, it needs to fire off an event with a reference to a modeler manager. Any listeners should listen and register javscript to load when the modeler renders.

When the modeler renders, it should load the modeler javascript, run any javascript that was registered, then finally load the bpmn file into the modeler.

This functionality will be used to assist in EXTENDING the modeler, especially registering new connectors.

**Comment by caleeli** [comment]
This issue was fixed with PR #942
