### ISSUE TITLE
Gateway Rules Feel Implementation 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#887]
Add the ability to evaluate gateway expressions to route task flow in Nayra. Should support all of the basic language elements. We should investigate if there is a Laravel package already for doing these evaluations.

https://docs.camunda.org/manual/7.4/reference/dmn11/feel/language-elements/

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/48375463-73fd4700-e69e-11e8-8d7b-ec088d6296a7.png)
