### ISSUE TITLE
Task Assignment API

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#917]
We need an API to add and update task assignments from the process. There is no delete functionality.

Acceptance Criteria

Unit test to add task assignment
Unity test to update a task assignment and return the new value
Annotate and Include in the Swagger documentation

**Comment by caleeli** [comment]
@velkymx @marcoAntonioNina, For the Modeler, I need a way to get the assigned users of a task. Also a way to add and remove assignments for that task:

![image](https://user-images.githubusercontent.com/8028650/48919014-afe69800-ee66-11e8-8b47-6ce4cd2c996c.png)
