### ISSUE TITLE
Document Uploading

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#922]
The form builder needs to be updated to include the form type (file) for uploading documents to our files API. 

- [x] Register a new type for the file upload element custom
- [x] Use the File Upload API #923
- [ ] Add a job to clean up orphaned files from the file storage

Once a task has the control it place, the output task in the request needs to upload the file on save to the media API and attached it to the request. 

A user should be able to see a list of documents attached to the request in a tab in the Request Details page. This page should have a table showing: Title, Date Uploaded and User Uploaded columns. When you click on the file title it should trigger the file download.

Acceptance Criteria

The flow of: 
- [x] Creating an input file in a form, saving, then running a request
- [x] attaching a document
- [x] loading the request detail, viewing the files
- [x] confirm downloading the document uploaded.

**Comment by milaendo** [comment]
Im not sure what to do with the job to clean the orphaned files
