### ISSUE TITLE
File Upload API

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#923]
Add an API end point for uploading files using the laravel media library. We should have full CRUD functionality. 

https://docs.spatie.be/laravel-medialibrary/v7/introduction

Acceptance Criteria

Unit test to list files
Unit test to get file
Unit test to add file
Unit test to delete a file
Annotate and Include in the Swagger documentation

**Comment by milaendo** [comment]
For the update method it is not possible to directly update the media file. So you'd delete the media referenced, and store a new media and then return the new media id here is a reference https://github.com/spatie/laravel-medialibrary/issues/762

**Comment by milaendo** [comment]
what has been done: 

index method is complete and tested
store method is complete and tested

**Comment by milaendo** [comment]
annotations will be done on another ticket so that we can move forward with the internal release

**Comment by velkymx** [comment]
This form control needs some TLC to match our UI. Let's discuss.
