### ISSUE TITLE
If Request starts with Script task, it is not routed forward

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#964]
This sounds similar to #581. A request that begins with a script task, say, Get Available Days, wont present the upcoming task. So, no way to know whether it run at all. The list of tasks remains blank, where it should have routed to the upcoming task and presented it in the list for the request to continue.

**Comment by danloa** [comment]
@velkymx this issue is already solved. Our default process has an script task as first task and works correctly.

**Comment by milaendo** [comment]
confirmed this is fixed
