### ISSUE TITLE
After replacing a task user assignment, task still assigns to old value.

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#966]
Created a simple request with a task assigned to admin user. Ran ok. Edited the process, changed to task assignment to another user. Re-ran the request. Task was assigned to original user and not the new one.

Here is the current task assignment definition:

<img width="1698" alt="screen shot 2018-11-30 at 10 28 43 am" src="https://user-images.githubusercontent.com/45466841/49307921-8a234980-f48b-11e8-98b8-f09acb9c5d43.png">

And here is the current task as it was assigned: -notice the different user

<img width="1698" alt="screen shot 2018-11-30 at 10 28 22 am" src="https://user-images.githubusercontent.com/45466841/49307941-9d361980-f48b-11e8-99db-51d0055ea2ef.png">

**Comment by danloa** [comment]
@velkymx the user interface for assignments now is very different. Any assignment problem in the modeler should be resolved with #1060
