### ISSUE TITLE
Beta Final Changes

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#967]
- [x] File Upload Menu Icon alignment
- [x] Permissions UI Grid
- [x] Modeler without lanes
- [x] Merge PRs
- [x] Remove Leave / Vacation Request
- [x] Duplicate ENV Vars
- [x] Remove Action Buttons that don't work
- [x] Remove groups tab from Edit User screen
- [x] Permission seeder for forms -> screens

**Comment by velkymx** [comment]
Permission UI Grid

**Comment by nolanpro** [comment]
Env vars and permission seeder

**Comment by nolanpro** [comment]
Also going to Remove Leave / Vacation Request since i'm working on seeders anyway

**Comment by danloa** [comment]
I'm going to work with Remove groups tab from Edit User screen

**Comment by nolanpro** [comment]
Committed removing Leave and Vacation Request to branch. This also fixes duplicate env vars and screen names.

**Comment by velkymx** [comment]
Permission Grid completed
