### ISSUE TITLE
User Assignments dont Work so cant enable a user to start a request.

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#969]
A user that does not have open, blank permissions cannot start a request, even after being specifically selected as an assigned user for the first task of the process.

Note the assigned user here:

<img width="1772" alt="screen shot 2018-11-30 at 10 59 10 am" src="https://user-images.githubusercontent.com/45466841/49309121-053a2f00-f48f-11e8-8763-62fdfeacc700.png">

and then when the same user tries to start that request:

<img width="1772" alt="screen shot 2018-11-30 at 11 00 18 am" src="https://user-images.githubusercontent.com/45466841/49309164-29960b80-f48f-11e8-8695-7ccaa1a5a2a2.png">

**Comment by danloa** [comment]
@velkymx The assignmet interface now is very differente. The issue of starting a process with a user should be resolved with  [#1060](https://github.com/ProcessMaker/bpm/issues/1060)
