### ISSUE TITLE
Admin user stopped being able to start requests all of the sudden

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#970]
After starting several requests, the admin user has suddenly stopped being able to start requests. Nothing has been touched on the frontend in terms of permissions, assignments for the admin user, etc.

Now I am getting this: 

<img width="1698" alt="screen shot 2018-11-30 at 11 25 01 am" src="https://user-images.githubusercontent.com/45466841/49310314-cf974500-f492-11e8-997d-e09ad54c879c.png">

**Comment by josemaldonad0** [comment]
Ok no other users can start any requests. It stopped working for all of them altogether.

**Comment by milaendo** [comment]
I have not been able to reproduce this error.
