### ISSUE TITLE
Screen Status

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#973]
We need a way to disable screens. By setting the status of a screen to inactive, this will remove it from all drop downs. We need more discussion around what to show in a process if a screen is selected, but set to inactive @tdondich

**Comment by tdondich** [comment]
What's the use case for having a screen be disabled?  Is there any reason why a screen should ever be disabled?

**Comment by velkymx** [comment]
If I have an old screen I don't want to use anymore.

**Comment by tdondich** [comment]
Wouldn't you remove it from the process to replace it with your new one first?  Why would you make the previous screen inactive before?

So, I would say, if the screen is inactive, can just provide/render "Screen (id) not found or inactive."

**Comment by velkymx** [comment]
@tdondich what if we check if the screen is being used before we allow disabling of the screen? We can add clear messaging "You cannot disable this screen, it is currently in use" maybe list the processes using it?

**Comment by velkymx** [comment]
Closing until we come up with something better
