### ISSUE TITLE
Form Preview only shows first page

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#982]
In the Screen Builder, the Preview feature will only show first page for forms with more than one page. Will present no option to switch between pages or else access the other pages beyond the first.

**Comment by tdondich** [comment]
@josemaldonad0 Page navigation is done via the navigation buttons.  There is no visible tabs as tab/pages do not have to be done in order.  In order to navigate to a page, add a navigation button and choose the target page.
