### ISSUE TITLE
ERROR: textAnnotation 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#998]
[2018-12-05 20:54:43] staging.ERROR: textAnnotation {"userId":1,"email":"udickens@hotmail.com","exception":"[object] (ProcessMaker\\Nayra\\Exceptions\\ElementNotImplementedException(code: 0): textAnnotation at /home/circleci/builds/develop-demo/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Storage/BpmnElement.php:42)
[stacktrace]
#0 /home/circleci/builds/develop-demo/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Storage/BpmnElement.php(93): ProcessMaker\\Nayra\\Storage\\BpmnElement->getBpmnElementInstance(Object(ProcessMaker\\Nayra\\Bpmn\\Models\\Process))
#1 /home/circleci/builds/develop-demo/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Storage/BpmnElement.php(76): ProcessMaker\\Nayra\\Storage\\BpmnElement->loadChildElements(Object(ProcessMaker\\Nayra\\Bpmn\\Models\\Process), Array)
#2 /home/circleci/builds/develop-demo/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Storage/BpmnDocument.php(493): ProcessMaker\\Nayra\\Storage\\BpmnElement->getBpmnElementInstance()
#3 /home/circleci/builds/develop-demo/vendor/processmaker/nayra/src/ProcessMaker/Nayra/Storage/BpmnElement.php(66): ProcessMaker\\Nayra\\Storage\\BpmnDocument->getElementInstanceById('ProcessId')
#4 /home/circleci/builds/develop-demo/ProcessMaker/Models/Process.php(332): ProcessMaker\\Nayra\\Storage\\BpmnElement->getBpmnElementInstance()
#5 /home/circleci/builds/develop-demo/ProcessMaker/Models/ProcessEvents.php(73): ProcessMaker\\Models\\Process->getStartEvents()
#6 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(564): ProcessMaker\\Models\\ProcessEvents->match(Array, Object(Illuminate\\Database\\Eloquent\\Collection), 'events')
#7 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(533): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'events', Object(Closure))
#8 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(501): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#9 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(746): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#10 /home/circleci/builds/develop-demo/ProcessMaker/Http/Controllers/Api/ProcessController.php(82): Illuminate\\Database\\Eloquent\\Builder->paginate(10)
#11 [internal function]: ProcessMaker\\Http\\Controllers\\Api\\ProcessController->index(Object(Illuminate\\Http\\Request))
#12 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /home/circleci/builds/develop-demo/ProcessMaker/Http/Controllers/Controller.php(42): Illuminate\\Routing\\Controller->callAction('index', Array)
#14 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): ProcessMaker\\Http\\Controllers\\Controller->callAction('index', Array)
#15 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(ProcessMaker\\Http\\Controllers\\Api\\ProcessController), 'index')
#16 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#18 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/circleci/builds/develop-demo/ProcessMaker/Http/Middleware/Authorize.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): ProcessMaker\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#27 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/circleci/builds/develop-demo/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/circleci/builds/develop-demo/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /home/circleci/builds/develop-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#56 /home/circleci/builds/develop-demo/public/index.php(11): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#57 {main}

**Comment by pawan-saxena** [comment]
What this error actually is and how can i reproduce it (in any way possible)  ?
